-- Classic dungeons
INSERT INTO `armory_instance_template` (`map`, `name_ru_ru`, `name_en_gb`, `expansion`, `boss_num`) 
VALUES
(531, 'Ан''Кираж', 'Ahn''Qiraj', 0, 12),
(469, 'Логово Крыла Тьмы', 'Blackwing Lair', 0, 8),
(409, 'Огненные Недра', 'Molten Core', 0, 10),
(509, 'Руины Ан''Киража', 'Ruins of Ahn''Qiraj', 0, 6),
(309, 'Зул''Гуруб', 'Zul''Gurub', 0, 9),
(48, 'Непроглядная Пучина', 'Blackfathom Deeps', 0, 8),
(229, 'Пик Черной горыа', 'Blackrock Spire', 0, 26),
(230, 'Глубины Черной горы', '', 0, 37),
(36, 'Мертвые копи', 'Deadmines', 0, 12),
(429, 'Забытый Город', 'Dire Maul', 0, 23),
(90, 'Гномреган', 'Gnomeregan', 0, 7),
(349, 'Мародон', 'Maraudon', 0, 10),
(389, 'Огненная пропасть', 'Ragefire Chasm', 0, 5),
(129, 'Курганы Иглошкурых', 'Razorfen Downs', 0, 6),
(47, 'Лабиринты Иглошкурых', 'Razorfen Kraul', 0, 8),
(189, 'Монастырь Алого ордена', 'Scarlet Monastery', 0, 11),
(289, 'Некроситет', 'Scholomance', 0, 15),
(33, 'Крепость Темного Клыка', 'Shadowfang Keep', 0, 9),
(34, 'Тюрьма', 'Stormwind Stockade', 0, 6),
(329, 'Стратхольм', 'Stratholme', 0, 23),
(109, 'Затонувший храм', 'Sunken Temple', 0, 20),
(70, 'Ульдаман', 'Uldaman', 0, 13),
(43, 'Пещеры Стенаний', 'Wailing Caverns', 0, 11),
(209, 'Зул''Фаррак', 'Zul''Farrak', 0, 13);

-- The Burning Crusadee expansion dungeons
INSERT INTO `armory_instance_template` (`map`, `name_ru_ru`, `name_en_gb`, `expansion`, `boss_num`) 
VALUES
(580, 'Плато Солнечного Колодца', 'The Sunwell', 1, 7),
(564, 'Черный храм', 'Black Temple', 1, 12),
(534, 'Битва за гору Хиджал', 'The Battle for Mount Hyjal', 1, 5),
(550, 'Крепость Бурь', 'Tempest Keep', 1, 4),
(548, 'Змеиное святилище', 'Serpentshrine Cavern', 1, 6),
(568, 'Зул''Аман', 'Zul''Aman', 1, 10),
(544, 'Логово Магтеридона', 'Magtheridon''s Lair', 1, 1),
(565, 'Логово Груула', 'Gruul''s Lair', 1, 2),
(532, 'Каражан', 'Karazhan', 1, 17),
(585, 'Терраса Магистров', 'Magisters'' Terrace', 1, 4),
(552, 'Аркатрац', 'Arcatraz', 1, 4),
(558, 'Аукенайские гробницы', 'Auchenai Crypts', 1, 2),
(-1, 'Черные топи', 'Black Morass', 1, 3),
(542, 'Кузня Крови', 'Blood Furnace', 1, 3),
(553, 'Ботаника', 'Botanica', 1, 5),
(543, 'Бастионы Адского Пламени', 'Hellfire Ramparts', 1, 3),
(557, 'Гробницы Маны', 'Mana-Tombs', 1, 3),
(554, 'Механар', 'Mechanar', 1, 6),
(-2, 'Старые предгорья Хилсбрада', 'Old Hillsbrad Foothills', 1, 3),
(556, 'Сетеккские залы', 'Sethekk Halls', 1, 2),
(555, 'Темный лабиринт', 'Shadow Labyrinth', 1, 4),
(540, 'Разрушенные залы', 'Shattered Halls', 1, 4),
(547, 'Узилище', 'Slave Pens', 1, 3),
(545, 'Паровое подземелье', 'Steamvault', 1, 3),
(546, 'Нижетопь', 'Underbog', 1, 4);

-- Wrath of the Lich King expansion dungeons
INSERT INTO `armory_instance_template` (`map`, `name_ru_ru`, `name_en_gb`, `expansion`, `boss_num`) 
VALUES
(631, 'Цитадель Ледяной Короны (25)', 'Icecrown Citadel (25)', 2, 12),
(631, 'Цитадель Ледяной Короны (10)', 'Icecrown Citadel (10)', 2, 12),
(632, 'Кузня Душ', 'The Forge of Souls', 2, 2),
(658, 'Яма Сарона', 'Pit of Saron', 2, 3),
(668, 'Залы Отражений', 'Halls of Reflection', 2, 3),
(249, 'Логово Ониксии', 'Onyxia''s Lair', 2, 1),
(649, 'Испытание крестоносца (25)', 'Trial of the Crusader (25)', 2, 6),
(649, 'Испытание крестоносца (10)', 'Trial of the Crusader (10)', 2, 6),
(650, 'Испытание чемпиона', 'Trial of the Champion', 2, 4),
(603, 'Ульдуар', 'Ulduar', 2, 16),
(616, 'Око Вечности', 'The Eye of Eternity', 2, 1),
(615, 'Обсидиановое святилище', 'The Obsidian Sanctum', 2, 1),
(533, 'Наксрамас', 'Naxxramas', 2, 15),
(624, 'Склеп Аркавона', 'Vault of Archavon', 2, 2),
(595, 'Очищение Стратхольма', 'The Culling of Stratholme', 2, 5),
(602, 'Чертоги Молний', 'Halls of Lightning', 2, 4),
(578, 'Окулус', 'The Oculus', 2, 4),
(575, 'Вершина Утгард', 'Utgarde Pinnacle', 2, 4),
(599, 'Чертоги Камня', 'Halls of Stone', 2, 4),
(604, 'Гундрак', 'Gundrak', 2, 4),
(608, 'Аметистовая крепость', 'Violet Hold', 2, 7),
(600, 'Крепость Драк''Тарон', 'Drak''Tharon Keep', 2, 4),
(619, 'Ан''кахет: Старое Королевство', 'Ahn''kahet: The Old Kingdom', 2, 5),
(601, 'Азжол-Неруб', 'Azjol-Nerub', 2, 3),
(576, 'Нексус', 'The Nexus', 2, 4),
(574, 'Крепость Утгард', 'Utgarde Keep', 2, 4);