INSERT INTO `armory_instance_template` VALUES
(509, 'Руины Ан''Киража', 'Ruins of Ahn''Qiraj', 0, 0),
(509, 'Руины Ан''Киража', 'Ruins of Ahn''Qiraj', 0, 0),
(509, 'Руины Ан''Киража', 'Ruins of Ahn''Qiraj', 0, 0),
(509, 'Руины Ан''Киража', 'Ruins of Ahn''Qiraj', 0, 0),
(509, 'Руины Ан''Киража', 'Ruins of Ahn''Qiraj', 0, 0),
(509, 'Руины Ан''Киража', 'Ruins of Ahn''Qiraj', 0, 0),
(509, 'Руины Ан''Киража', 'Ruins of Ahn''Qiraj', 0, 0),
(509, 'Руины Ан''Киража', 'Ruins of Ahn''Qiraj', 0, 0),
(509, 'Руины Ан''Киража', 'Ruins of Ahn''Qiraj', 0, 0),
(509, 'Руины Ан''Киража', 'Ruins of Ahn''Qiraj', 0, 0),
(509, 'Руины Ан''Киража', 'Ruins of Ahn''Qiraj', 0, 0),
(509, 'Руины Ан''Киража', 'Ruins of Ahn''Qiraj', 0, 0),
(509, 'Руины Ан''Киража', 'Ruins of Ahn''Qiraj', 0, 0),
(509, 'Руины Ан''Киража', 'Ruins of Ahn''Qiraj', 0, 0),