/*!40101 SET NAMES utf8 */;
/*!40101 SET SQL_MODE=''*/;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP TABLE IF EXISTS `maps`;
CREATE TABLE `maps` (
  `id` int(11) NOT NULL,
  `name_ru_ru` varchar(255) NOT NULL,
  `name_en_gb` varchar(255) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `maps` VALUES (0, 'Восточные королевства', 'Eastern Kingdoms');
INSERT INTO `maps` VALUES (1, 'Калимдор', 'Kalimdor');
INSERT INTO `maps` VALUES (13, 'Тестирование', 'Testing');
INSERT INTO `maps` VALUES (25, 'Тест Скотта', 'Scott Test');
INSERT INTO `maps` VALUES (29, 'Тест: деньги', 'CashTest');
INSERT INTO `maps` VALUES (30, 'Альтеракская долина', 'Alterac Valley');
INSERT INTO `maps` VALUES (33, 'Крепость Темного Клыка', 'Shadowfang Keep');
INSERT INTO `maps` VALUES (34, 'Тюрьма Штормграда', 'Stormwind Stockade');
INSERT INTO `maps` VALUES (35, ' Тюрьма Штормграда', 'StormwindPrison');
INSERT INTO `maps` VALUES (36, 'Мертвые копи', 'Deadmines');
INSERT INTO `maps` VALUES (37, 'Кратер Азшары', 'Azshara Crater');
INSERT INTO `maps` VALUES (42, 'Тест Коллина', 'Collin''s Test');
INSERT INTO `maps` VALUES (43, 'Пещеры Стенаний', 'Wailing Caverns');
INSERT INTO `maps` VALUES (44, ' Монастырь', ' Monastery');
INSERT INTO `maps` VALUES (47, 'Лабиринты Иглошкурых', 'Razorfen Kraul');
INSERT INTO `maps` VALUES (48, 'Непроглядная Пучина', 'Blackfathom Deeps');
INSERT INTO `maps` VALUES (70, 'Ульдаман', 'Uldaman');
INSERT INTO `maps` VALUES (90, 'Гномреган', 'Gnomeregan');
INSERT INTO `maps` VALUES (109, 'Затонувший храм', 'Sunken Temple');
INSERT INTO `maps` VALUES (129, 'Курганы Иглошкурых', 'Razorfen Downs');
INSERT INTO `maps` VALUES (169, 'Изумрудный Сон', 'Emerald Dream');
INSERT INTO `maps` VALUES (189, 'Монастырь Алого ордена', 'Scarlet Monastery');
INSERT INTO `maps` VALUES (209, 'Зул''Фаррак', 'Zul''Farrak');
INSERT INTO `maps` VALUES (229, 'Пик Черной горы', 'Blackrock Spire');
INSERT INTO `maps` VALUES (230, 'Глубины Черной горы', 'Blackrock Depths');
INSERT INTO `maps` VALUES (249, 'Логово Ониксии', 'Onyxia''s Lair');
INSERT INTO `maps` VALUES (269, 'Открытие Темного портала', 'Opening of the Dark Portal');
INSERT INTO `maps` VALUES (289, 'Некроситет', 'Scholomance');
INSERT INTO `maps` VALUES (309, 'Зул''Гуруб', 'Zul''Gurub');
INSERT INTO `maps` VALUES (329, 'Стратхольм', 'Stratholme');
INSERT INTO `maps` VALUES (349, 'Мародон', 'Maraudon');
INSERT INTO `maps` VALUES (369, 'Подземный поезд', 'Deeprun Tram');
INSERT INTO `maps` VALUES (389, 'Огненная пропасть', 'Ragefire Chasm');
INSERT INTO `maps` VALUES (409, 'Огненные Недра', 'Molten Core');
INSERT INTO `maps` VALUES (429, 'Забытый Город', 'Dire Maul');
INSERT INTO `maps` VALUES (449, 'Казармы Альянса', 'Alliance PVP Barracks');
INSERT INTO `maps` VALUES (450, 'Казармы Орды', 'Horde PVP Barracks');
INSERT INTO `maps` VALUES (451, 'Зона разработчика', 'Development Land');
INSERT INTO `maps` VALUES (469, 'Логово Крыла Тьмы', 'Blackwing Lair');
INSERT INTO `maps` VALUES (489, 'Ущелье Песни Войны', 'Warsong Gulch');
INSERT INTO `maps` VALUES (509, 'Руины Ан''Киража', 'Ruins of Ahn''Qiraj');
INSERT INTO `maps` VALUES (529, 'Низина Арати', 'Arathi Basin');
INSERT INTO `maps` VALUES (530, 'Запределье', 'Outland');
INSERT INTO `maps` VALUES (531, 'Храм Ан''Киража', 'Ahn''Qiraj Temple');
INSERT INTO `maps` VALUES (532, 'Каражан', 'Karazhan');
INSERT INTO `maps` VALUES (533, 'Наксрамас', 'Naxxramas');
INSERT INTO `maps` VALUES (534, 'Битва за гору Хиджал', 'The Battle for Mount Hyjal');
INSERT INTO `maps` VALUES (540, 'Цитадель Адского Пламени: Разрушенные залы', 'Hellfire Citadel: The Shattered Halls');
INSERT INTO `maps` VALUES (542, 'Цитадель Адского Пламени: Кузня Крови', 'Hellfire Citadel: The Blood Furnace');
INSERT INTO `maps` VALUES (543, 'Цитадель Адского Пламени: Бастионы', 'Hellfire Citadel: Ramparts');
INSERT INTO `maps` VALUES (544, 'Логово Магтеридона', 'Magtheridon''s Lair');
INSERT INTO `maps` VALUES (545, 'Кривой Клык: Паровое подземелье', 'Coilfang: The Steamvault');
INSERT INTO `maps` VALUES (546, 'Кривой Клык: Нижетопь', 'Coilfang: The Underbog');
INSERT INTO `maps` VALUES (547, 'Кривой Клык: Узилище', 'Coilfang: The Slave Pens');
INSERT INTO `maps` VALUES (548, 'Кривой Клык: Змеиное святилище', 'Coilfang: Serpentshrine Cavern');
INSERT INTO `maps` VALUES (550, 'Крепость Бурь', 'Tempest Keep');
INSERT INTO `maps` VALUES (552, 'Крепость Бурь: Аркатрац', 'Tempest Keep: The Arcatraz');
INSERT INTO `maps` VALUES (553, 'Крепость Бурь: Ботаника', 'Tempest Keep: The Botanica');
INSERT INTO `maps` VALUES (554, 'Крепость Бурь – Механар', 'Tempest Keep: The Mechanar');
INSERT INTO `maps` VALUES (555, 'Аукиндон: Темный лабиринт', 'Auchindoun: Shadow Labyrinth');
INSERT INTO `maps` VALUES (556, 'Аукиндон: Сетеккские залы', 'Auchindoun: Sethekk Halls');
INSERT INTO `maps` VALUES (557, 'Аукиндон: Гробницы Маны', 'Auchindoun: Mana-Tombs');
INSERT INTO `maps` VALUES (558, 'Аукиндон: Аукенайские гробницы', 'Auchindoun: Auchenai Crypts');
INSERT INTO `maps` VALUES (559, 'Арена Награнда', 'Nagrand Arena');
INSERT INTO `maps` VALUES (560, 'Побег из Дарнхольда', 'The Escape From Durnholde');
INSERT INTO `maps` VALUES (562, 'Арена Острогорья', 'Blade''s Edge Arena');
INSERT INTO `maps` VALUES (564, 'Черный храм', 'Black Temple');
INSERT INTO `maps` VALUES (565, 'Логово Груула', 'Gruul''s Lair');
INSERT INTO `maps` VALUES (566, 'Око Бури', 'Eye of the Storm');
INSERT INTO `maps` VALUES (568, 'Зул''Аман', 'Zul''Aman');
INSERT INTO `maps` VALUES (571, 'Нордскол', 'Northrend');
INSERT INTO `maps` VALUES (572, 'Руины Лордерона', 'Ruins of Lordaeron');
INSERT INTO `maps` VALUES (573, 'ExteriorTest', 'ExteriorTest');
INSERT INTO `maps` VALUES (574, 'Крепость Утгард', 'Utgarde Keep');
INSERT INTO `maps` VALUES (575, 'Вершина Утгард', 'Utgarde Pinnacle');
INSERT INTO `maps` VALUES (576, 'Нексус', 'The Nexus');
INSERT INTO `maps` VALUES (578, 'Окулус', 'The Oculus');
INSERT INTO `maps` VALUES (580, 'Солнечный Колодец', 'The Sunwell');
INSERT INTO `maps` VALUES (582, 'Перевозка: из Рут''терана в Аубердин', 'Transport: Rut''theran to Auberdine');
INSERT INTO `maps` VALUES (584, 'Перевозка: из Менетила на Терамор', 'Transport: Menethil to Theramore');
INSERT INTO `maps` VALUES (585, 'Терраса Магистров', 'Magister''s Terrace');
INSERT INTO `maps` VALUES (586, 'Перевозка: из Экзодара в Аубердин', 'Transport: Exodar to Auberdine');
INSERT INTO `maps` VALUES (587, 'Перевозка: Переправа Оперенной Луны', 'Transport: Feathermoon Ferry');
INSERT INTO `maps` VALUES (588, 'Перевозка: из Менетила в Аубердин', 'Transport: Menethil to Auberdine');
INSERT INTO `maps` VALUES (589, 'Перевозка: из Оргриммара в Гром''гол', 'Transport: Orgrimmar to Grom''Gol');
INSERT INTO `maps` VALUES (590, 'Перевозка: из Гром''гола в Подгород', 'Transport: Grom''Gol to Undercity');
INSERT INTO `maps` VALUES (591, 'Перевозка: из Подгорода в Оргриммар', 'Transport: Undercity to Orgrimmar');
INSERT INTO `maps` VALUES (592, 'Перевозка: Борейская тундра (тест)', 'Transport: Borean Tundra Test');
INSERT INTO `maps` VALUES (593, 'Перевозка: из Пиратской бухты в Кабестан', 'Transport: Booty Bay to Ratchet');
INSERT INTO `maps` VALUES (594, 'Перевозка: Сестры милосердия Ревущего фьорда (задание)', 'Transport: Howling Fjord Sister Mercy (Quest)');
INSERT INTO `maps` VALUES (595, 'Очищение Стратхольма', 'The Culling of Stratholme');
INSERT INTO `maps` VALUES (596, 'Перевозка: (Наглфар)', 'Transport: Naglfar');
INSERT INTO `maps` VALUES (597, 'Craig Test', 'Craig Test');
INSERT INTO `maps` VALUES (598, 'Солнечный Колодец стабилизированный (не используется)', 'Sunwell Fix (Unused)');
INSERT INTO `maps` VALUES (599, 'Чертоги Камня', 'Halls of Stone');
INSERT INTO `maps` VALUES (600, 'Крепость Драк''Тарон', 'Drak''Tharon Keep');
INSERT INTO `maps` VALUES (601, 'Азжол-Неруб', 'Azjol-Nerub');
INSERT INTO `maps` VALUES (602, 'Чертоги Молний', 'Halls of Lightning');
INSERT INTO `maps` VALUES (603, 'Ульдуар', 'Ulduar');
INSERT INTO `maps` VALUES (604, 'Гундрак', 'Gundrak');
INSERT INTO `maps` VALUES (605, 'Development Land (non-weighted textures)', 'Development Land (non-weighted textures)');
INSERT INTO `maps` VALUES (606, 'QA and DVD', 'QA and DVD');
INSERT INTO `maps` VALUES (607, 'Берег Древних', 'Strand of the Ancients');
INSERT INTO `maps` VALUES (608, 'Аметистовая крепость', 'Violet Hold');
INSERT INTO `maps` VALUES (609, 'Черный оплот', 'Ebon Hold');
INSERT INTO `maps` VALUES (610, 'Транспорт: из Тирисфаля к Лагерю Возмездия', 'Transport: Tirisfal to Vengeance Landing');
INSERT INTO `maps` VALUES (612, 'Транспорт: из Менетила к Вангарду', 'Transport: Menethil to Valgarde');
INSERT INTO `maps` VALUES (613, 'Транспорт: из Оргриммара к Крепости Песни Войны', 'Transport: Orgrimmar to Warsong Hold');
INSERT INTO `maps` VALUES (614, 'Транспорт: из Штормграда к Крепости Отваги', 'Transport: Stormwind to Valiance Keep');
INSERT INTO `maps` VALUES (615, 'Обсидиановое святилище', 'The Obsidian Sanctum');
INSERT INTO `maps` VALUES (616, 'Око вечности', 'The Eye of Eternity');
INSERT INTO `maps` VALUES (617, 'Стоки Даларана', 'Dalaran Sewers');
INSERT INTO `maps` VALUES (618, 'Арена Доблести', 'The Ring of Valor');
INSERT INTO `maps` VALUES (619, 'Ан''кахет: Старое королевство', 'Ahn''kahet: The Old Kingdom');
INSERT INTO `maps` VALUES (620, 'Транспорт: из Моа''ки в Уну''пе', 'Transport: Moa''ki to Unu''pe');
INSERT INTO `maps` VALUES (621, 'Транспорт: из Моа''ки в Камагуа', 'Transport: Moa''ki to Kamagua');
INSERT INTO `maps` VALUES (622, 'Транспорт: Молот Оргрима', 'Transport: Orgrim''s Hammer');
INSERT INTO `maps` VALUES (623, 'Транспорт: Усмиритель небес', 'Transport: The Skybreaker');
INSERT INTO `maps` VALUES (624, 'Склеп Аркавона', 'Vault of Archavon');
INSERT INTO `maps` VALUES (628, 'Остров Завоеваний', 'Isle of Conquest');
INSERT INTO `maps` VALUES (631, 'Цитадель Ледяной Короны', 'Icecrown Citadel');
INSERT INTO `maps` VALUES (632, 'Кузня Душ', 'The Forge of Souls');
INSERT INTO `maps` VALUES (641, 'Transport: Alliance Airship BG', 'Transport: Alliance Airship BG');
INSERT INTO `maps` VALUES (642, 'Transport: HordeAirshipBG', 'Transport: HordeAirshipBG');
INSERT INTO `maps` VALUES (647, 'Транспорт: из Оргриммара в Громовой Утес', 'Transport: Orgrimmar to Thunder Bluff');
INSERT INTO `maps` VALUES (649, 'Испытание крестоносца', 'Trial of the Crusader');
INSERT INTO `maps` VALUES (650, 'Испытание чемпиона', 'Trial of the Champion');
INSERT INTO `maps` VALUES (658, 'Яма Сарона', 'Pit of Saron');
INSERT INTO `maps` VALUES (668, 'Залы Отражений', 'Halls of Reflection');
INSERT INTO `maps` VALUES (672, 'Транспорт: Усмиритель небес (рейды в Цитадели Ледяной Короны)', 'Transport: The Skybreaker (Icecrown Citadel Raid)');
INSERT INTO `maps` VALUES (673, 'Транспорт: Молот Оргрима (рейды в Цитадели Ледяной Короны)', 'Transport: Orgrim''s Hammer (Icecrown Citadel Raid)');
INSERT INTO `maps` VALUES (712, 'Транспорт: Усмиритель небес (подземелья Цитадели Ледяной Короны)', 'Transport: The Skybreaker (IC Dungeon)');
INSERT INTO `maps` VALUES (713, 'Транспорт: Молот Оргрима (подземелья Цитадели Ледяной Короны)', 'Transport: Orgrim''s Hammer (IC Dungeon)');
INSERT INTO `maps` VALUES (718, 'Транспорт: Могучий ветер (Цитадель Ледяной Короны, рейд)', 'Trasnport: The Mighty Wind (Icecrown Citadel Raid)');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;