<?php

/**
 * @package World of Warcraft Armory
 * @version Release Candidate 1
 * @revision 30
 * @copyright (c) 2009-2010 Shadez  
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 **/

if(!defined('__ARMORY__')) {
    die('Direct access to this file not allowed!');
}

// Auto generated for version 3.2.2.10505

/*** Classes ***/
define('CLASS_WARRIOR', 0x01);
define('CLASS_PALADIN', 0x02);
define('CLASS_HUNTER',  0x03);
define('CLASS_ROGUE',   0x04);
define('CLASS_PRIEST',  0x05);
define('CLASS_DK',      0x06);
define('CLASS_SHAMAN',  0x07);
define('CLASS_MAGE',    0x08);
define('CLASS_WARLOCK', 0x09);
define('CLASS_DRUID',   0x0A);

/*** Races ***/
define('RACE_HUMAN',    0x01);
define('RACE_ORC',      0x02);
define('RACE_DWARF',    0x03);
define('RACE_NIGHTELF', 0x04);
define('RACE_UNDEAD',   0x05);
define('RACE_TAUREN',   0x06);
define('RACE_GNOM',     0x07);
define('RACE_TROLL',    0x08);
define('RACE_BLOODELF', 0x0A);
define('RACE_DRAENEI',  0x0B);

/*** Achievements ***/
define('ACH_MAX_COUNT_GAME', 986);
define('ACH_MAX_COUNT_GENERAL', 54);
define('ACH_MAX_COUNT_QUESTS', 49);
define('ACH_MAX_COUNT_QUESTS_GENERAL', 9);
define('ACH_MAX_COUNT_QUESTS_CLASSIC', 3);
define('ACH_MAX_COUNT_QUESTS_TBC', 11);
define('ACH_MAX_COUNT_QUESTS_WOTLK', 17);
define('ACH_MAX_COUNT_QUESTS_CATACLYSM', 0);
define('ACH_MAX_COUNT_EXPLORATION_GENERAL', 5);
define('ACH_MAX_COUNT_EXPLORATION_EK', 25);
define('ACH_MAX_COUNT_EXPLORATION_KALIMDOR', 20);
define('ACH_MAX_COUNT_EXPLORATION_OUTLAND', 8);
define('ACH_MAX_COUNT_EXPLORATION_NORTHREND', 10);
define('ACH_MAX_COUNT_EXPLORATION_CATACLYSM', 0);
define('ACH_MAX_COUNT_PVP_GENERAL', 24);
define('ACH_MAX_COUNT_PVP_ARENA', 13);
define('ACH_MAX_COUNT_PVP_AV', 13);
define('ACH_MAX_COUNT_PVP_AB', 14);
define('ACH_MAX_COUNT_PVP_EOTS', 12);
define('ACH_MAX_COUNT_PVP_WG', 14);
define('ACH_MAX_COUNT_PVP_SA', 14);
define('ACH_MAX_COUNT_PVP_WINTERGRASP', 18);
define('ACH_MAX_COUNT_PVP_IC', 13);
define('ACH_MAX_COUNT_DUNGEONS_GENERAL', 19);
define('ACH_MAX_COUNT_DUNGEONS_CLASSIC', 26);
define('ACH_MAX_COUNT_DUNGEONS_TBC', 41);
define('ACH_MAX_COUNT_DUNGEONS_WOTLK', 13);
define('ACH_MAX_COUNT_DUNGEONS_WOTLK_H', 55);
define('ACH_MAX_COUNT_DUNGEONS_WOTLK_RAID', 33);
define('ACH_MAX_COUNT_DUNGEONS_WOTLK_RAID_H', 33);
define('ACH_MAX_COUNT_DUNGEONS_ULDUAR_RAID', 62);
define('ACH_MAX_COUNT_DUNGEONS_ULDUAR_RAID_H', 61);
define('ACH_MAX_COUNT_DUNGEONS_CRUSADE', 9);
define('ACH_MAX_COUNT_DUNGEONS_CRUSADE_H', 9);
define('ACH_MAX_COUNT_PROFESSIONS_GENERAL', 3);
define('ACH_MAX_COUNT_PROFESSIONS_COOKING', 14);
define('ACH_MAX_COUNT_PROFESSIONS_FISHING', 24);
define('ACH_MAX_COUNT_PROFESSIONS_FIRST_AID', 3);
define('ACH_MAX_COUNT_REPUTATION_GENERAL', 6);
define('ACH_MAX_COUNT_REPUTATION_CLASSIC', 5);
define('ACH_MAX_COUNT_REPUTATION_TBC', 14);
define('ACH_MAX_COUNT_REPUTATION_WOTLK', 12);
define('ACH_MAX_COUNT_REPUTATION_CATACLYSM', 0); // Lol :)
define('ACH_MAX_COUNT_EVENTS_GENERAL', 12);
define('ACH_MAX_COUNT_EVENTS_LUNAR_FESTIVAL', 11);
define('ACH_MAX_COUNT_EVENTS_LOVE', 14);
define('ACH_MAX_COUNT_EVENTS_NOBLEGARDEN', 10);
define('ACH_MAX_COUNT_EVENTS_CHILDRENS', 7);
define('ACH_MAX_COUNT_EVENTS_MIDSUMMER', 12);
define('ACH_MAX_COUNT_EVENTS_BREWFEST', 10);
define('ACH_MAX_COUNT_EVENTS_HALLOWEEN', 16);
define('ACH_MAX_COUNT_EVENTS_PILIGIRIM', 9);
define('ACH_MAX_COUNT_EVENTS_WINTER_VEIL', 13);
define('ACH_MAX_COUNT_EVENTS_ARGENT_TOURNAMENT', 12);
define('ACH_MAX_COUNT_FEATS_OF_STRENGHT', 142);

// Categories
define('ACH_CATEGORY_GENERAL', 92);
define('ACH_CATEGORY_QUESTS', 96);
define('ACH_CATEGORY_QUESTS_EA', 14861);
define('ACH_CATEGORY_QUESTS_TBC', 14862);
define('ACH_CATEGORY_QUESTS_WOTLK', 14863);
define('ACH_CATEGORY_QUESTS_CATACLYSM', 0);
define('ACH_CATEGORY_EXPLORATION', 97);
define('ACH_CATEGORY_EXPLORATION_EK', 14777);
define('ACH_CATEGORY_EXPLORATION_KALIMDOR', 14778);
define('ACH_CATEGORY_EXPLORATION_OUTLAND', 14779);
define('ACH_CATEGORY_EXPLORATION_NORTHREND', 14780);
define('ACH_CATEGORY_EXPLORATION_CATACLYSM', 0);
define('ACH_CATEGORY_PVP', 95);
define('ACH_CATEGORY_PVP_ARENA', 165);
define('ACH_CATEGORY_PVP_AV', 14801);
define('ACH_CATEGORY_PVP_AB', 14802);
define('ACH_CATEGORY_PVP_EOTS', 14803);
define('ACH_CATEGORY_PVP_WG', 14804);
define('ACH_CATEGORY_PVP_SA', 14881);
define('ACH_CATEGORY_PVP_WINTERGRASP', 14901);
define('ACH_CATEGORY_PVP_IC', 15003);
define('ACH_CATEGORY_DUNGEONS', 168);
define('ACH_CATEGORY_DUNGEONS_CLASSIC', 14808);
define('ACH_CATEGORY_DUNGEONS_TBC', 14805);
define('ACH_CATEGORY_DUNGEONS_WOTLK', 14806);
define('ACH_CATEGORY_DUNGEONS_WOTLK_H', 14921);
define('ACH_CATEGORY_DUNGEONS_WOTLK_RAID', 14922);
define('ACH_CATEGORY_DUNGEONS_WOTLK_RAID_H', 14923);
define('ACH_CATEGORY_DUNGEONS_ULDUAR', 14961);
define('ACH_CATEGORY_DUNGEONS_ULDUAR_H', 14962);
define('ACH_CATEGORY_DUNGEONS_CRUSADE', 15001);
define('ACH_CATEGORY_DUNGEONS_CRUSADE_H', 15002);
define('ACH_CATEGORY_PROFESSIONS', 169);
define('ACH_CATEGORY_PROFESSIONS_COOKING', 170);
define('ACH_CATEGORY_PROFESSIONS_FISHING', 171);
define('ACH_CATEGORY_PROFESSIONS_FIRST_AID', 172);
define('ACH_CATEGORY_REPUTATION', 201);
define('ACH_CATEGORY_REPUTATION_CLASSIC', 14864);
define('ACH_CATEGORY_REPUTATION_TBC', 14865);
define('ACH_CATEGORY_REPUTATION_WOTLK', 14866);
define('ACH_CATEGORY_REPUTATION_CATACLYSM', 0);
define('ACH_CATEGORY_EVENTS', 155);
define('ACH_CATEGORY_EVENTS_LUNAR_FESTIVAL', 160);
define('ACH_CATEGORY_EVENTS_LOVE', 187);
define('ACH_CATEGORY_EVENTS_NOBLEGARDEN', 159);
define('ACH_CATEGORY_EVENTS_CHILDRENS', 163);
define('ACH_CATEGORY_EVENTS_MIDSUMMER', 161);
define('ACH_CATEGORY_EVENTS_BREWFEST', 162);
define('ACH_CATEGORY_EVENTS_HALLOWEEN', 158);
define('ACH_CATEGORY_EVENTS_PILIGRIM', 14981);
define('ACH_CATEGORY_EVENTS_WINTER_VEIL', 156);
define('ACH_CATEGORY_EVENTS_ARGENT_TOURNAMENT', 14941);
define('ACH_CATEGORY_FEATS_OF_STRENGHT', 81);

// Count
define('ACH_COUNT_QUESTS', ACH_MAX_COUNT_QUESTS_GENERAL + ACH_MAX_COUNT_QUESTS_CLASSIC + 
   ACH_MAX_COUNT_QUESTS_TBC + ACH_MAX_COUNT_QUESTS_WOTLK + 
   ACH_MAX_COUNT_QUESTS_CATACLYSM);
define('ACH_COUNT_EXPLORATION', ACH_MAX_COUNT_EXPLORATION_GENERAL + ACH_MAX_COUNT_EXPLORATION_EK + 
ACH_MAX_COUNT_EXPLORATION_KALIMDOR + ACH_MAX_COUNT_EXPLORATION_OUTLAND + 
ACH_MAX_COUNT_EXPLORATION_NORTHREND + ACH_MAX_COUNT_EXPLORATION_CATACLYSM);
define('ACH_COUNT_PVP', ACH_MAX_COUNT_PVP_GENERAL + ACH_MAX_COUNT_PVP_ARENA + ACH_MAX_COUNT_PVP_AV + 
ACH_MAX_COUNT_PVP_AB + ACH_MAX_COUNT_PVP_EOTS + ACH_MAX_COUNT_PVP_WG + 
ACH_MAX_COUNT_PVP_SA + ACH_MAX_COUNT_PVP_WINTERGRASP + ACH_MAX_COUNT_PVP_IC);
define('ACH_COUNT_DUNGEONS', ACH_MAX_COUNT_DUNGEONS_GENERAL + ACH_MAX_COUNT_DUNGEONS_CLASSIC + ACH_MAX_COUNT_DUNGEONS_TBC +
 ACH_MAX_COUNT_DUNGEONS_WOTLK + ACH_MAX_COUNT_DUNGEONS_WOTLK_H + 
 ACH_MAX_COUNT_DUNGEONS_WOTLK_RAID + ACH_MAX_COUNT_DUNGEONS_WOTLK_RAID_H + 
 ACH_MAX_COUNT_DUNGEONS_ULDUAR_RAID + ACH_MAX_COUNT_DUNGEONS_ULDUAR_RAID_H +
 ACH_MAX_COUNT_DUNGEONS_CRUSADE + ACH_MAX_COUNT_DUNGEONS_CRUSADE_H);
define('ACH_COUNT_PROFESSIONS', ACH_MAX_COUNT_PROFESSIONS_GENERAL + ACH_MAX_COUNT_PROFESSIONS_COOKING +
ACH_MAX_COUNT_PROFESSIONS_FISHING + ACH_MAX_COUNT_PROFESSIONS_FIRST_AID);
define('ACH_COUNT_REPUTATION', ACH_MAX_COUNT_REPUTATION_GENERAL + ACH_MAX_COUNT_REPUTATION_CLASSIC +
   ACH_MAX_COUNT_REPUTATION_TBC + ACH_MAX_COUNT_REPUTATION_WOTLK +
   ACH_MAX_COUNT_REPUTATION_CATACLYSM);
define('ACH_COUNT_EVENTS', ACH_MAX_COUNT_EVENTS_GENERAL + ACH_MAX_COUNT_EVENTS_LUNAR_FESTIVAL +
   ACH_MAX_COUNT_EVENTS_LOVE + ACH_MAX_COUNT_EVENTS_NOBLEGARDEN +
   ACH_MAX_COUNT_EVENTS_CHILDRENS + ACH_MAX_COUNT_EVENTS_MIDSUMMER +
   ACH_MAX_COUNT_EVENTS_BREWFEST + ACH_MAX_COUNT_EVENTS_HALLOWEEN +
   ACH_MAX_COUNT_EVENTS_PILIGIRIM + ACH_MAX_COUNT_EVENTS_WINTER_VEIL +
   ACH_MAX_COUNT_EVENTS_ARGENT_TOURNAMENT);
   
/*** Skills ***/
define('SKILL_SWORDS', 43);
define('SKILL_AXES', 44);
define('SKILL_BOWS', 45);
define('SKILL_GUNS', 46);
define('SKILL_MACES', 54);
define('SKILL_TWO_HANDED_SWORDS', 55);
define('SKILL_DEFENCE', 95);
define('SKILL_DUAL_WIELD', 118);
define('SKILL_STAVES', 136);
define('SKILL_TWO_HANDED_MACES', 160);
define('SKILL_UNARMED', 162);
define('SKILL_TWO_HANDED_AXE', 172);
define('SKILL_DAGGERS', 173);
define('SKILL_THROWN', 176);
define('SKILL_CROSSBOWS', 226);
define('SKILL_WANDS', 228);
define('SKILL_POLEARMS', 229);
define('SKILL_FIST_WEAPONS', 473);

define('FACTION_FLAG_VISIBLE', 0x01);         // makes visible in client (set or can be set at interaction with target of this faction)
define('FACTION_FLAG_AT_WAR', 0x02);          // enable AtWar-button in client. player controlled (except opposition team always war state), Flag only set on initial creation
define('FACTION_FLAG_HIDDEN', 0x04);          // hidden faction from reputation pane in client (player can gain reputation, but this update not sent to client)
define('FACTION_FLAG_INVISIBLE_FORCED', 0x08);// always overwrite FACTION_FLAG_VISIBLE and hide faction in rep.list, used for hide opposite team factions
define('FACTION_FLAG_PEACE_FORCED', 0x10);    // always overwrite FACTION_FLAG_AT_WAR, used for prevent war with own team factions
define('FACTION_FLAG_INACTIVE', 0x20);        // player controlled, state
define('FACTION_FLAG_RIVAL', 0x40);           // flag for the two competing outland factions

define('STAT_STRENGTH', 0);
define('STAT_AGILITY', 1);
define('STAT_STAMINA', 2);
define('STAT_INTELLECT', 3);
define('STAT_SPIRIT', 4);

define('ATTACK_POWER_MAGIC_NUMBER',14);
define('BLOCK_PER_STRENGTH', 0.5);
define('HEALTH_PER_STAMINA', 10);
define('ARMOR_PER_AGILITY', 2);
define('MANA_PER_INTELLECT', 15);
define('MANA_REGEN_PER_SPIRIT', 0.2);
define('DODGE_PARRY_BLOCK_PERCENT_PER_DEFENSE', 0.04);
define('RESILIENCE_CRIT_CHANCE_TO_DAMAGE_REDUCTION_MULTIPLIER', 2.2);
define('PLAYER_FIELD_DODGE_RATING', PLAYER_FIELD_COMBAT_RATING_1+2);	// CR_DODGE
define('PLAYER_FIELD_PARRY_RATING', PLAYER_FIELD_COMBAT_RATING_1+3);	// CR_PARRY
define('PLAYER_FIELD_CRIT_TAKEN_MELEE_RATING', PLAYER_FIELD_COMBAT_RATING_1+14);	// CR_CRIT_TAKEN_MELEE
define('PLAYER_FIELD_CRIT_TAKEN_RANGED_RATING', PLAYER_FIELD_COMBAT_RATING_1+15);	// CR_CRIT_TAKEN_RANGED
define('PLAYER_FIELD_CRIT_TAKEN_SPELL_RATING', PLAYER_FIELD_COMBAT_RATING_1+16);	// CR_CRIT_TAKEN_SPELL
?>