<?php

/**
 * @package World of Warcraft Armory
 * @version Release Candidate 1
 * @revision 137
 * @copyright (c) 2009-2010 Shadez  
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 **/

if(!defined('__ARMORY__')) {
    die('Direct access to this file not allowed!');
}

/*** Classes ***/
define('CLASS_WARRIOR', 0x01);
define('CLASS_PALADIN', 0x02);
define('CLASS_HUNTER',  0x03);
define('CLASS_ROGUE',   0x04);
define('CLASS_PRIEST',  0x05);
define('CLASS_DK',      0x06);
define('CLASS_SHAMAN',  0x07);
define('CLASS_MAGE',    0x08);
define('CLASS_WARLOCK', 0x09);
define('CLASS_DRUID',   0x0A);

/*** Races ***/
define('RACE_HUMAN',    0x01);
define('RACE_ORC',      0x02);
define('RACE_DWARF',    0x03);
define('RACE_NIGHTELF', 0x04);
define('RACE_UNDEAD',   0x05);
define('RACE_TAUREN',   0x06);
define('RACE_GNOM',     0x07);
define('RACE_TROLL',    0x08);
define('RACE_BLOODELF', 0x0A);
define('RACE_DRAENEI',  0x0B);

/*** Achievements ***/
define('ACHIEVEMENTS_CATEGORY_GENERAL',     92);
define('ACHIEVEMENTS_CATEGORY_QUESTS',      96);
define('ACHIEVEMENTS_CATEGORY_EXPLORATION', 97);
define('ACHIEVEMENTS_CATEGORY_PVP',         95);
define('ACHIEVEMENTS_CATEGORY_DUNGEONS',    168);
define('ACHIEVEMENTS_CATEGORY_PROFESSIONS', 169);
define('ACHIEVEMENTS_CATEGORY_REPUTATION',  201);
define('ACHIEVEMENTS_CATEGORY_EVENTS',      155);
define('ACHIEVEMENTS_CATEGORY_FEATS',       81);

define('ACHIEVEMENTS_COUNT_SUMMARY',     1054);
define('ACHIEVEMENTS_COUNT_GENERAL',     54);
define('ACHIEVEMENTS_COUNT_QUESTS',      49);
define('ACHIEVEMENTS_COUNT_EXPLORATION', 70);
define('ACHIEVEMENTS_COUNT_PVP',         166);
define('ACHIEVEMENTS_COUNT_DUNGEONS',    454);
define('ACHIEVEMENTS_COUNT_PROFESSIONS', 75);
define('ACHIEVEMENTS_COUNT_REPUTATION',  45);
define('ACHIEVEMENTS_COUNT_EVENTS',      141);

define('ACHIEVEMENT_POINTS_SUMMARY',     11635);
define('ACHIEVEMENT_POINTS_GENERAL',     570);
define('ACHIEVEMENT_POINTS_QUESTS',      530);
define('ACHIEVEMENT_POINTS_EXPLORATION', 830);
define('ACHIEVEMENT_POINTS_PVP',         1930);
define('ACHIEVEMENT_POINTS_DUNGEONS',    4915);
define('ACHIEVEMENT_POINTS_PROFESSIONS', 760);
define('ACHIEVEMENT_POINTS_REPUTATION',  560);
define('ACHIEVEMENT_POINTS_EVENTS',      1540);

define('ACH_MAX_COUNT_GAME', 1054);
define('ACH_MAX_COUNT_GENERAL', 54);
define('ACH_MAX_COUNT_QUESTS', 49);
define('ACH_MAX_COUNT_QUESTS_GENERAL', 9);
define('ACH_MAX_COUNT_QUESTS_CLASSIC', 3);
define('ACH_MAX_COUNT_QUESTS_TBC', 11);
define('ACH_MAX_COUNT_QUESTS_WOTLK', 17);
define('ACH_MAX_COUNT_EXPLORATION_GENERAL', 5);
define('ACH_MAX_COUNT_EXPLORATION_EK', 25);
define('ACH_MAX_COUNT_EXPLORATION_KALIMDOR', 20);
define('ACH_MAX_COUNT_EXPLORATION_OUTLAND', 8);
define('ACH_MAX_COUNT_EXPLORATION_NORTHREND', 10);
define('ACH_MAX_COUNT_PVP_GENERAL', 31);
define('ACH_MAX_COUNT_PVP_ARENA', 25);
define('ACH_MAX_COUNT_PVP_AV', 14);
define('ACH_MAX_COUNT_PVP_AB', 15);
define('ACH_MAX_COUNT_PVP_EOTS', 13);
define('ACH_MAX_COUNT_PVP_WG', 15);
define('ACH_MAX_COUNT_PVP_SA', 15);
define('ACH_MAX_COUNT_PVP_WINTERGRASP', 23);
define('ACH_MAX_COUNT_PVP_IC', 15);
define('ACH_MAX_COUNT_DUNGEONS_GENERAL', 29);
define('ACH_MAX_COUNT_DUNGEONS_CLASSIC', 26);
define('ACH_MAX_COUNT_DUNGEONS_TBC', 41);
define('ACH_MAX_COUNT_DUNGEONS_WOTLK', 16);
define('ACH_MAX_COUNT_DUNGEONS_WOTLK_H', 62);
define('ACH_MAX_COUNT_DUNGEONS_WOTLK_RAID', 33);
define('ACH_MAX_COUNT_DUNGEONS_WOTLK_RAID_H', 33);
define('ACH_MAX_COUNT_DUNGEONS_ULDUAR_RAID', 71);
define('ACH_MAX_COUNT_DUNGEONS_ULDUAR_RAID_H', 70);
define('ACH_MAX_COUNT_DUNGEONS_CRUSADE', 12);
define('ACH_MAX_COUNT_DUNGEONS_CRUSADE_H', 11);
define('ACH_MAX_COUNT_DUNGEONS_FALL_OF_THE_LICH_KING', 25);
define('ACH_MAX_COUNT_DUNGEONS_FALL_OF_THE_LICH_KING_H', 25);
define('ACH_MAX_COUNT_PROFESSIONS_GENERAL', 7);
define('ACH_MAX_COUNT_PROFESSIONS_COOKING', 28);
define('ACH_MAX_COUNT_PROFESSIONS_FISHING', 33);
define('ACH_MAX_COUNT_PROFESSIONS_FIRST_AID', 7);
define('ACH_MAX_COUNT_REPUTATION_GENERAL', 13);
define('ACH_MAX_COUNT_REPUTATION_CLASSIC', 5);
define('ACH_MAX_COUNT_REPUTATION_TBC', 14);
define('ACH_MAX_COUNT_REPUTATION_WOTLK', 13);
define('ACH_MAX_COUNT_EVENTS_GENERAL', 12);
define('ACH_MAX_COUNT_EVENTS_LUNAR_FESTIVAL', 15);
define('ACH_MAX_COUNT_EVENTS_LOVE', 15);
define('ACH_MAX_COUNT_EVENTS_NOBLEGARDEN', 11);
define('ACH_MAX_COUNT_EVENTS_CHILDRENS', 7);
define('ACH_MAX_COUNT_EVENTS_MIDSUMMER', 12);
define('ACH_MAX_COUNT_EVENTS_BREWFEST', 10);
define('ACH_MAX_COUNT_EVENTS_HALLOWEEN', 16);
define('ACH_MAX_COUNT_EVENTS_PILIGIRIM', 9);
define('ACH_MAX_COUNT_EVENTS_WINTER_VEIL', 13);
define('ACH_MAX_COUNT_EVENTS_ARGENT_TOURNAMENT', 23);
define('ACH_MAX_COUNT_FEATS_OF_STRENGHT', 152);

// Categories
define('ACH_CATEGORY_GENERAL', 92);
define('ACH_CATEGORY_QUESTS', 96);
define('ACH_CATEGORY_QUESTS_EA', 14861);
define('ACH_CATEGORY_QUESTS_TBC', 14862);
define('ACH_CATEGORY_QUESTS_WOTLK', 14863);
define('ACH_CATEGORY_EXPLORATION', 97);
define('ACH_CATEGORY_EXPLORATION_EK', 14777);
define('ACH_CATEGORY_EXPLORATION_KALIMDOR', 14778);
define('ACH_CATEGORY_EXPLORATION_OUTLAND', 14779);
define('ACH_CATEGORY_EXPLORATION_NORTHREND', 14780);
define('ACH_CATEGORY_PVP', 95);
define('ACH_CATEGORY_PVP_ARENA', 165);
define('ACH_CATEGORY_PVP_AV', 14801);
define('ACH_CATEGORY_PVP_AB', 14802);
define('ACH_CATEGORY_PVP_EOTS', 14803);
define('ACH_CATEGORY_PVP_WG', 14804);
define('ACH_CATEGORY_PVP_SA', 14881);
define('ACH_CATEGORY_PVP_WINTERGRASP', 14901);
define('ACH_CATEGORY_PVP_IC', 15003);
define('ACH_CATEGORY_DUNGEONS', 168);
define('ACH_CATEGORY_DUNGEONS_CLASSIC', 14808);
define('ACH_CATEGORY_DUNGEONS_TBC', 14805);
define('ACH_CATEGORY_DUNGEONS_WOTLK', 14806);
define('ACH_CATEGORY_DUNGEONS_WOTLK_H', 14921);
define('ACH_CATEGORY_DUNGEONS_WOTLK_RAID', 14922);
define('ACH_CATEGORY_DUNGEONS_WOTLK_RAID_H', 14923);
define('ACH_CATEGORY_DUNGEONS_ULDUAR', 14961);
define('ACH_CATEGORY_DUNGEONS_ULDUAR_H', 14962);
define('ACH_CATEGORY_DUNGEONS_CRUSADE', 15001);
define('ACH_CATEGORY_DUNGEONS_CRUSADE_H', 15002);
define('ACH_CATEGORY_DUNGEONS_FALL_OF_THE_LICH_KING', 15041);
define('ACH_CATEGORY_DUNGEONS_FALL_OF_THE_LICH_KING_H', 15042);
define('ACH_CATEGORY_PROFESSIONS', 169);
define('ACH_CATEGORY_PROFESSIONS_COOKING', 170);
define('ACH_CATEGORY_PROFESSIONS_FISHING', 171);
define('ACH_CATEGORY_PROFESSIONS_FIRST_AID', 172);
define('ACH_CATEGORY_REPUTATION', 201);
define('ACH_CATEGORY_REPUTATION_CLASSIC', 14864);
define('ACH_CATEGORY_REPUTATION_TBC', 14865);
define('ACH_CATEGORY_REPUTATION_WOTLK', 14866);
define('ACH_CATEGORY_EVENTS', 155);
define('ACH_CATEGORY_EVENTS_LUNAR_FESTIVAL', 160);
define('ACH_CATEGORY_EVENTS_LOVE', 187);
define('ACH_CATEGORY_EVENTS_NOBLEGARDEN', 159);
define('ACH_CATEGORY_EVENTS_CHILDRENS', 163);
define('ACH_CATEGORY_EVENTS_MIDSUMMER', 161);
define('ACH_CATEGORY_EVENTS_BREWFEST', 162);
define('ACH_CATEGORY_EVENTS_HALLOWEEN', 158);
define('ACH_CATEGORY_EVENTS_PILIGRIM', 14981);
define('ACH_CATEGORY_EVENTS_WINTER_VEIL', 156);
define('ACH_CATEGORY_EVENTS_ARGENT_TOURNAMENT', 14941);
define('ACH_CATEGORY_FEATS_OF_STRENGHT', 81);

// Count
define('ACH_COUNT_QUESTS', ACH_MAX_COUNT_QUESTS_GENERAL + ACH_MAX_COUNT_QUESTS_CLASSIC + 
   ACH_MAX_COUNT_QUESTS_TBC + ACH_MAX_COUNT_QUESTS_WOTLK);
define('ACH_COUNT_EXPLORATION', ACH_MAX_COUNT_EXPLORATION_GENERAL + ACH_MAX_COUNT_EXPLORATION_EK + 
ACH_MAX_COUNT_EXPLORATION_KALIMDOR + ACH_MAX_COUNT_EXPLORATION_OUTLAND + 
ACH_MAX_COUNT_EXPLORATION_NORTHREND);
define('ACH_COUNT_PVP', ACH_MAX_COUNT_PVP_GENERAL + ACH_MAX_COUNT_PVP_ARENA + ACH_MAX_COUNT_PVP_AV + 
ACH_MAX_COUNT_PVP_AB + ACH_MAX_COUNT_PVP_EOTS + ACH_MAX_COUNT_PVP_WG + 
ACH_MAX_COUNT_PVP_SA + ACH_MAX_COUNT_PVP_WINTERGRASP + ACH_MAX_COUNT_PVP_IC);
define('ACH_COUNT_DUNGEONS', ACH_MAX_COUNT_DUNGEONS_GENERAL + ACH_MAX_COUNT_DUNGEONS_CLASSIC + ACH_MAX_COUNT_DUNGEONS_TBC +
 ACH_MAX_COUNT_DUNGEONS_WOTLK + ACH_MAX_COUNT_DUNGEONS_WOTLK_H + 
 ACH_MAX_COUNT_DUNGEONS_WOTLK_RAID + ACH_MAX_COUNT_DUNGEONS_WOTLK_RAID_H + 
 ACH_MAX_COUNT_DUNGEONS_ULDUAR_RAID + ACH_MAX_COUNT_DUNGEONS_ULDUAR_RAID_H +
 ACH_MAX_COUNT_DUNGEONS_CRUSADE + ACH_MAX_COUNT_DUNGEONS_CRUSADE_H + ACH_MAX_COUNT_DUNGEONS_FALL_OF_THE_LICH_KING + ACH_MAX_COUNT_DUNGEONS_FALL_OF_THE_LICH_KING_H);
define('ACH_COUNT_PROFESSIONS', ACH_MAX_COUNT_PROFESSIONS_GENERAL + ACH_MAX_COUNT_PROFESSIONS_COOKING +
ACH_MAX_COUNT_PROFESSIONS_FISHING + ACH_MAX_COUNT_PROFESSIONS_FIRST_AID);
define('ACH_COUNT_REPUTATION', ACH_MAX_COUNT_REPUTATION_GENERAL + ACH_MAX_COUNT_REPUTATION_CLASSIC +
   ACH_MAX_COUNT_REPUTATION_TBC + ACH_MAX_COUNT_REPUTATION_WOTLK);
define('ACH_COUNT_EVENTS', ACH_MAX_COUNT_EVENTS_GENERAL + ACH_MAX_COUNT_EVENTS_LUNAR_FESTIVAL +
   ACH_MAX_COUNT_EVENTS_LOVE + ACH_MAX_COUNT_EVENTS_NOBLEGARDEN +
   ACH_MAX_COUNT_EVENTS_CHILDRENS + ACH_MAX_COUNT_EVENTS_MIDSUMMER +
   ACH_MAX_COUNT_EVENTS_BREWFEST + ACH_MAX_COUNT_EVENTS_HALLOWEEN +
   ACH_MAX_COUNT_EVENTS_PILIGIRIM + ACH_MAX_COUNT_EVENTS_WINTER_VEIL +
   ACH_MAX_COUNT_EVENTS_ARGENT_TOURNAMENT);
   
/*** Skills ***/
define('SKILL_SWORDS', 43);
define('SKILL_AXES', 44);
define('SKILL_BOWS', 45);
define('SKILL_GUNS', 46);
define('SKILL_MACES', 54);
define('SKILL_TWO_HANDED_SWORDS', 55);
define('SKILL_DEFENCE', 95);
define('SKILL_DUAL_WIELD', 118);
define('SKILL_STAVES', 136);
define('SKILL_TWO_HANDED_MACES', 160);
define('SKILL_UNARMED', 162);
define('SKILL_TWO_HANDED_AXE', 172);
define('SKILL_DAGGERS', 173);
define('SKILL_THROWN', 176);
define('SKILL_CROSSBOWS', 226);
define('SKILL_WANDS', 228);
define('SKILL_POLEARMS', 229);
define('SKILL_FIST_WEAPONS', 473);

define('FACTION_FLAG_VISIBLE', 0x01);         // makes visible in client (set or can be set at interaction with target of this faction)
define('FACTION_FLAG_AT_WAR', 0x02);          // enable AtWar-button in client. player controlled (except opposition team always war state), Flag only set on initial creation
define('FACTION_FLAG_HIDDEN', 0x04);          // hidden faction from reputation pane in client (player can gain reputation, but this update not sent to client)
define('FACTION_FLAG_INVISIBLE_FORCED', 0x08);// always overwrite FACTION_FLAG_VISIBLE and hide faction in rep.list, used for hide opposite team factions
define('FACTION_FLAG_PEACE_FORCED', 0x10);    // always overwrite FACTION_FLAG_AT_WAR, used for prevent war with own team factions
define('FACTION_FLAG_INACTIVE', 0x20);        // player controlled, state
define('FACTION_FLAG_RIVAL', 0x40);           // flag for the two competing outland factions

define('STAT_STRENGTH', 0);
define('STAT_AGILITY', 1);
define('STAT_STAMINA', 2);
define('STAT_INTELLECT', 3);
define('STAT_SPIRIT', 4);

define('ATTACK_POWER_MAGIC_NUMBER',14);
define('BLOCK_PER_STRENGTH', 0.5);
define('HEALTH_PER_STAMINA', 10);
define('ARMOR_PER_AGILITY', 2);
define('MANA_PER_INTELLECT', 15);
define('MANA_REGEN_PER_SPIRIT', 0.2);
define('DODGE_PARRY_BLOCK_PERCENT_PER_DEFENSE', 0.04);
define('RESILIENCE_CRIT_CHANCE_TO_DAMAGE_REDUCTION_MULTIPLIER', 2.2);
define('PLAYER_FIELD_DODGE_RATING', PLAYER_FIELD_COMBAT_RATING_1+2);	// CR_DODGE
define('PLAYER_FIELD_PARRY_RATING', PLAYER_FIELD_COMBAT_RATING_1+3);	// CR_PARRY
define('PLAYER_FIELD_CRIT_TAKEN_MELEE_RATING', PLAYER_FIELD_COMBAT_RATING_1+14);	// CR_CRIT_TAKEN_MELEE
define('PLAYER_FIELD_CRIT_TAKEN_RANGED_RATING', PLAYER_FIELD_COMBAT_RATING_1+15);	// CR_CRIT_TAKEN_RANGED
define('PLAYER_FIELD_CRIT_TAKEN_SPELL_RATING', PLAYER_FIELD_COMBAT_RATING_1+16);	// CR_CRIT_TAKEN_SPELL


/** Achievement criteria types **/
define('ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE', 0);
define('ACHIEVEMENT_CRITERIA_TYPE_WIN_BG',        1);
define('ACHIEVEMENT_CRITERIA_TYPE_REACH_LEVEL', 5);
define('ACHIEVEMENT_CRITERIA_TYPE_REACH_SKILL_LEVEL', 7);
define('ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_ACHIEVEMENT', 8);
define('ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST_COUNT', 9);
define('ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_DAILY_QUEST_DAILY', 10);
define('ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUESTS_IN_ZONE', 11);
define('ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_DAILY_QUEST', 14);
define('ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_BATTLEGROUND', 15);
define('ACHIEVEMENT_CRITERIA_TYPE_DEATH_AT_MAP',  16);
define('ACHIEVEMENT_CRITERIA_TYPE_DEATH_IN_DUNGEON', 18);
define('ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_RAID', 19);
define('ACHIEVEMENT_CRITERIA_TYPE_KILLED_BY_CREATURE', 20);
define('ACHIEVEMENT_CRITERIA_TYPE_FALL_WITHOUT_DYING', 24);
define('ACHIEVEMENT_CRITERIA_TYPE_DEATHS_FROM', 26);
define('ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST', 27);
define('ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET', 28);
define('ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET2', 69);
define('ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL', 29);
define('ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL_AT_AREA', 31);
define('ACHIEVEMENT_CRITERIA_TYPE_WIN_ARENA', 32);
define('ACHIEVEMENT_CRITERIA_TYPE_PLAY_ARENA', 33);
define('ACHIEVEMENT_CRITERIA_TYPE_LEARN_SPELL', 34);
define('ACHIEVEMENT_CRITERIA_TYPE_OWN_ITEM', 36);
define('ACHIEVEMENT_CRITERIA_TYPE_WIN_RATED_ARENA', 37);
define('ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_TEAM_RATING', 38);
define('ACHIEVEMENT_CRITERIA_TYPE_REACH_TEAM_RATING', 39);
define('ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILL_LEVEL', 40);
define('ACHIEVEMENT_CRITERIA_TYPE_USE_ITEM', 41);
define('ACHIEVEMENT_CRITERIA_TYPE_LOOT_ITEM', 42);
define('ACHIEVEMENT_CRITERIA_TYPE_EXPLORE_AREA', 43);
define('ACHIEVEMENT_CRITERIA_TYPE_OWN_RANK', 44);
define('ACHIEVEMENT_CRITERIA_TYPE_BUY_BANK_SLOT', 45);
define('ACHIEVEMENT_CRITERIA_TYPE_GAIN_REPUTATION', 46);
define('ACHIEVEMENT_CRITERIA_TYPE_GAIN_EXALTED_REPUTATION', 47);
define('ACHIEVEMENT_CRITERIA_TYPE_VISIT_BARBER_SHOP', 48);
define('ACHIEVEMENT_CRITERIA_TYPE_EQUIP_EPIC_ITEM', 49);
define('ACHIEVEMENT_CRITERIA_TYPE_ROLL_NEED_ON_LOOT', 50);
define('ACHIEVEMENT_CRITERIA_TYPE_ROLL_GREED_ON_LOOT', 51);
define('ACHIEVEMENT_CRITERIA_TYPE_HK_CLASS', 52);
define('ACHIEVEMENT_CRITERIA_TYPE_HK_RACE', 53);
define('ACHIEVEMENT_CRITERIA_TYPE_DO_EMOTE', 54);
define('ACHIEVEMENT_CRITERIA_TYPE_DAMAGE_DONE', 13);
define('ACHIEVEMENT_CRITERIA_TYPE_HEALING_DONE', 55);
define('ACHIEVEMENT_CRITERIA_TYPE_GET_KILLING_BLOWS', 56);
define('ACHIEVEMENT_CRITERIA_TYPE_EQUIP_ITEM', 57);
define('ACHIEVEMENT_CRITERIA_TYPE_MONEY_FROM_QUEST_REWARD', 62);
define('ACHIEVEMENT_CRITERIA_TYPE_LOOT_MONEY', 67);
define('ACHIEVEMENT_CRITERIA_TYPE_USE_GAMEOBJECT', 68);
define('ACHIEVEMENT_CRITERIA_TYPE_SPECIAL_PVP_KILL', 70);
define('ACHIEVEMENT_CRITERIA_TYPE_FISH_IN_GAMEOBJECT', 72);
define('ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILLLINE_SPELLS', 75);
define('ACHIEVEMENT_CRITERIA_TYPE_WIN_DUEL', 76);
define('ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_POWER', 96);
define('ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_STAT', 97);
define('ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_SPELLPOWER', 98);
define('ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_RATING', 100);
define('ACHIEVEMENT_CRITERIA_TYPE_LOOT_TYPE', 109);
define('ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILL_LINE', 112);
define('ACHIEVEMENT_CRITERIA_TYPE_EARN_HONORABLE_KILL', 113);
define('ACHIEVEMENT_CRITERIA_TYPE_LFD_PASSED', 119);

define('ACHIEVEMENT_FLAG_COUNTER', 0x0001);
define('ACHIEVEMENT_FLAG_UNK2', 0x0002);
define('ACHIEVEMENT_FLAG_MAX_VALUE', 0x0004);
define('ACHIEVEMENT_FLAG_SUMM', 0x0008);
define('ACHIEVEMENT_FLAG_MAX_USED', 0x0010);
define('ACHIEVEMENT_FLAG_REQ_COUNT', 0x0020);
define('ACHIEVEMENT_FLAG_AVERANGE', 0x0040);
define('ACHIEVEMENT_FLAG_BAR', 0x0080);
define('ACHIEVEMENT_FLAG_REALM_FIRST_REACH', 0x0100); 
define('ACHIEVEMENT_FLAG_REALM_FIRST_KILL', 0x0200);
define('ACHIEVEMENT_CRITERIA_FLAG_SHOW_PROGRESS_BAR', 0x00000001);
define('ACHIEVEMENT_CRITERIA_FLAG_HIDE_CRITERIA', 0x00000002);
define('ACHIEVEMENT_CRITERIA_FLAG_UNK3', 0x00000004);
define('ACHIEVEMENT_CRITERIA_FLAG_UNK4', 0x00000008);
define('ACHIEVEMENT_CRITERIA_FLAG_UNK5', 0x00000010);
define('ACHIEVEMENT_CRITERIA_FLAG_MONEY_COUNTER', 0x00000020);
define('CUSTOM_ACHIEVEMENT_SHOW', ACHIEVEMENT_FLAG_SUMM|ACHIEVEMENT_FLAG_MAX_USED|ACHIEVEMENT_FLAG_REQ_COUNT);

define('ITEM_FIELD_ENCHANTMENT_3_2', ITEM_FIELD_ENCHANTMENT_3_1+1);
define('ITEM_FIELD_ENCHANTMENT_4_2', ITEM_FIELD_ENCHANTMENT_4_1+1);
define('ITEM_FIELD_ENCHANTMENT_5_2', ITEM_FIELD_ENCHANTMENT_5_1+1);
define('ITEM_FIELD_ENCHANTMENT_6_2', ITEM_FIELD_ENCHANTMENT_6_1+1);

define('INV_HEAD', 0);
define('INV_NECK', 1);
define('INV_SHOULDER', 2);
define('INV_SHIRT', 3);
define('INV_CHEST', 4);
define('INV_BELT', 5);
define('INV_LEGS', 6);
define('INV_BOOTS', 7);
define('INV_BRACERS', 8);
define('INV_GLOVES', 9);
define('INV_RING_1', 10);
define('INV_RING_2', 11);
define('INV_TRINKET_1', 12);
define('INV_TRINKET_2', 13);
define('INV_BACK', 14);
define('INV_MAIN_HAND', 15);
define('INV_OFF_HAND', 16);
define('INV_RANGED_RELIC', 17);
define('INV_TABARD', 18);

/* Character feed */
define('TYPE_ACHIEVEMENT_FEED', 1);
define('TYPE_ITEM_FEED',        2);
define('TYPE_BOSS_FEED',        3);

/* Item classes */
define('ITEM_CLASS_CONSUMABLE', 0);
define('ITEM_CLASS_CONTAINER', 1);
define('ITEM_CLASS_WEAPON', 2);
define('ITEM_CLASS_GEM', 3);
define('ITEM_CLASS_ARMOR', 4);
define('ITEM_CLASS_REAGENT', 5);
define('ITEM_CLASS_PROJECTILE', 6);
define('ITEM_CLASS_TRADE_GOODS', 7);
define('ITEM_CLASS_GENERIC', 8);
define('ITEM_CLASS_RECIPE', 9);
define('ITEM_CLASS_MONEY', 10);
define('ITEM_CLASS_QUIVER', 11);
define('ITEM_CLASS_QUEST', 12);
define('ITEM_CLASS_KEY', 13);
define('ITEM_CLASS_PERMANENT', 14);
define('ITEM_CLASS_MISC', 15);
define('ITEM_CLASS_GLYPH', 16);
?>