<xsl-template name="head-content">
<script src="_js/tools/talent-calc.js" type="text/javascript"></script>
</xsl-template>
<script type="text/javascript">
		var talentData_sdfkte75 = [
		
			{
				id:   "Discipline",
				name: "Discipline",
				talents: [
				
					{
						id:     342,
						tier:   0,
						column: 1,
						name:  "Unbreakable Will",
						icon:  "spell_magic_magearmor",
						
						ranks: [
						
							"Reduces the duration of Stun, Fear, and Silence effects done to you by an additional 6%."
							,
							"Reduces the duration of Stun, Fear, and Silence effects done to you by an additional 12%."
							,
							"Reduces the duration of Stun, Fear, and Silence effects done to you by an additional 18%."
							,
							"Reduces the duration of Stun, Fear, and Silence effects done to you by an additional 24%."
							,
							"Reduces the duration of Stun, Fear, and Silence effects done to you by an additional 30%."
							
						]
					}
					,
					{
						id:     1898,
						tier:   0,
						column: 2,
						name:  "Twin Disciplines",
						icon:  "spell_holy_sealofvengeance",
						
						ranks: [
						
							"Increases the damage and healing done by your instant spells by 1%."
							,
							"Increases the damage and healing done by your instant spells by 2%."
							,
							"Increases the damage and healing done by your instant spells by 3%."
							,
							"Increases the damage and healing done by your instant spells by 4%."
							,
							"Increases the damage and healing done by your instant spells by 5%."
							
						]
					}
					,
					{
						id:     352,
						tier:   1,
						column: 0,
						name:  "Silent Resolve",
						icon:  "spell_nature_manaregentotem",
						
						ranks: [
						
							"Reduces the threat generated by your Holy and Discipline spells by 7% and reduces the chance your helpful spells and damage over time effects will be dispelled by 10%."
							,
							"Reduces the threat generated by your Holy and Discipline spells by 14% and reduces the chance your helpful spells and damage over time effects will be dispelled by 20%."
							,
							"Reduces the threat generated by your Holy and Discipline spells by 20% and reduces the chance your helpful spells and damage over time effects will be dispelled by 30%."
							
						]
					}
					,
					{
						id:     346,
						tier:   1,
						column: 1,
						name:  "Improved Inner Fire",
						icon:  "spell_holy_innerfire",
						
						ranks: [
						
							"Increases the effect of your Inner Fire spell by 15%, and increases the total number of charges by 4."
							,
							"Increases the effect of your Inner Fire spell by 30%, and increases the total number of charges by 8."
							,
							"Increases the effect of your Inner Fire spell by 45%, and increases the total number of charges by 12."
							
						]
					}
					,
					{
						id:     344,
						tier:   1,
						column: 2,
						name:  "Improved Power Word: Fortitude",
						icon:  "spell_holy_wordfortitude",
						
						ranks: [
						
							"Increases the effect of your Power Word: Fortitude and Prayer of Fortitude spells by 15%, and increases your total Stamina by 2%."
							,
							"Increases the effect of your Power Word: Fortitude and Prayer of Fortitude spells by 30%, and increases your total Stamina by 4%."
							
						]
					}
					,
					{
						id:     321,
						tier:   1,
						column: 3,
						name:  "Martyrdom",
						icon:  "spell_nature_tranquility",
						
						ranks: [
						
							"Gives you a 50% chance to gain the Focused Casting effect that lasts for 6 sec after being the victim of a melee or ranged critical strike.  The Focused Casting effect reduces the pushback suffered from damaging attacks while casting Priest spells and decreases the duration of Interrupt effects by 10%."
							,
							"Gives you a 100% chance to gain the Focused Casting effect that lasts for 6 sec after being the victim of a melee or ranged critical strike.  The Focused Casting effect reduces the pushback suffered from damaging attacks while casting Priest spells and decreases the duration of Interrupt effects by 20%."
							
						]
					}
					,
					{
						id:     347,
						tier:   2,
						column: 0,
						name:  "Meditation",
						icon:  "spell_nature_sleep",
						
						ranks: [
						
							"Allows 17% of your mana regeneration to continue while casting."
							,
							"Allows 33% of your mana regeneration to continue while casting."
							,
							"Allows 50% of your mana regeneration to continue while casting."
							
						]
					}
					,
					{
						id:     348,
						tier:   2,
						column: 1,
						name:  "Inner Focus",
						icon:  "spell_frost_windwalkon",
						
						ranks: [
						
							"When activated, reduces the mana cost of your next spell by 100% and increases its critical effect chance by 25% if it is capable of a critical effect."
							
						]
					}
					,
					{
						id:     343,
						tier:   2,
						column: 2,
						name:  "Improved Power Word: Shield",
						icon:  "spell_holy_powerwordshield",
						
						ranks: [
						
							"Increases the damage absorbed by your Power Word: Shield by 5%."
							,
							"Increases the damage absorbed by your Power Word: Shield by 10%."
							,
							"Increases the damage absorbed by your Power Word: Shield by 15%."
							
						]
					}
					,
					{
						id:     1769,
						tier:   3,
						column: 0,
						name:  "Absolution",
						icon:  "spell_holy_absolution",
						
						ranks: [
						
							"Reduces the mana cost of your Dispel Magic, Cure Disease, Abolish Disease and Mass Dispel spells by 5%."
							,
							"Reduces the mana cost of your Dispel Magic, Cure Disease, Abolish Disease and Mass Dispel spells by 10%."
							,
							"Reduces the mana cost of your Dispel Magic, Cure Disease, Abolish Disease and Mass Dispel spells by 15%."
							
						]
					}
					,
					{
						id:     341,
						tier:   3,
						column: 1,
						name:  "Mental Agility",
						icon:  "ability_hibernation",
						
						ranks: [
						
							"Reduces the mana cost of your instant cast spells by 4%."
							,
							"Reduces the mana cost of your instant cast spells by 7%."
							,
							"Reduces the mana cost of your instant cast spells by 10%."
							
						]
					}
					,
					{
						id:     350,
						tier:   3,
						column: 3,
						name:  "Improved Mana Burn",
						icon:  "spell_shadow_manaburn",
						
						ranks: [
						
							"Reduces the casting time of your Mana Burn spell by 0.5 sec."
							,
							"Reduces the casting time of your Mana Burn spell by 1 sec."
							
						]
					}
					,
					{
						id:     2268,
						tier:   4,
						column: 0,
						name:  "Reflective Shield",
						icon:  "spell_holy_powerwordshield",
						
						ranks: [
						
							"Causes 22% of the damage you absorb with Power Word: Shield to reflect back at the attacker.  This damage causes no threat."
							,
							"Causes 45% of the damage you absorb with Power Word: Shield to reflect back at the attacker.  This damage causes no threat."
							
						]
					}
					,
					{
						id:     1201,
						tier:   4,
						column: 1,
						name:  "Mental Strength",
						icon:  "spell_nature_enchantarmor",
						
						ranks: [
						
							"Increases your total Intellect by 3%."
							,
							"Increases your total Intellect by 6%."
							,
							"Increases your total Intellect by 9%."
							,
							"Increases your total Intellect by 12%."
							,
							"Increases your total Intellect by 15%."
							
						]
					}
					,
					{
						id:     351,
						tier:   4,
						column: 2,
						name:  "Soul Warding",
						icon:  "spell_holy_pureofheart",
						
							requires: 343,
						
						ranks: [
						
							"Reduces the cooldown of your Power Word: Shield ability by 4 sec, and reduces the mana cost of your Power Word: Shield by 15%."
							
						]
					}
					,
					{
						id:     1771,
						tier:   5,
						column: 0,
						name:  "Focused Power",
						icon:  "spell_shadow_focusedpower",
						
						ranks: [
						
							"Increases damage and healing done by your spells by 2%. In addition, your Mass Dispel cast time is reduced by 0.5 sec."
							,
							"Increases damage and healing done by your spells by 4%. In addition, your Mass Dispel cast time is reduced by 1 sec."
							
						]
					}
					,
					{
						id:     1772,
						tier:   5,
						column: 2,
						name:  "Enlightenment",
						icon:  "spell_arcane_mindmastery",
						
						ranks: [
						
							"Increases your total Spirit by 2% and increases your spell haste by 2%."
							,
							"Increases your total Spirit by 4% and increases your spell haste by 4%."
							,
							"Increases your total Spirit by 6% and increases your spell haste by 6%."
							
						]
					}
					,
					{
						id:     1858,
						tier:   6,
						column: 0,
						name:  "Focused Will",
						icon:  "spell_arcane_focusedpower",
						
						ranks: [
						
							"Increases your spell critical effect chance by 1%, and after taking a critical hit you gain the Focused Will effect, reducing all damage taken by 2% and increasing healing effects on you by 3%.  Stacks up to 3 times.  Lasts 8 sec."
							,
							"Increases your spell critical effect chance by 2%, and after taking a critical hit you gain the Focused Will effect, reducing all damage taken by 3% and increasing healing effects on you by 4%.  Stacks up to 3 times.  Lasts 8 sec."
							,
							"Increases your spell critical effect chance by 3%, and after taking a critical hit you gain the Focused Will effect, reducing all damage taken by 4% and increasing healing effects on you by 5%.  Stacks up to 3 times.  Lasts 8 sec."
							
						]
					}
					,
					{
						id:     322,
						tier:   6,
						column: 1,
						name:  "Power Infusion",
						icon:  "spell_holy_powerinfusion",
						
							requires: 1201,
						
						ranks: [
						
							"Infuses the target with power, increasing spell casting speed by 20% and reducing the mana cost of all spells by 20%.  Lasts 15 sec."
							
						]
					}
					,
					{
						id:     1773,
						tier:   6,
						column: 2,
						name:  "Improved Flash Heal",
						icon:  "spell_holy_chastise",
						
						ranks: [
						
							"Reduces the mana cost of your Flash Heal by 5%, and increases the critical effect chance of your Flash Heal by 4% on friendly targets at or below 50% health."
							,
							"Reduces the mana cost of your Flash Heal by 10%, and increases the critical effect chance of your Flash Heal by 7% on friendly targets at or below 50% health."
							,
							"Reduces the mana cost of your Flash Heal by 15%, and increases the critical effect chance of your Flash Heal by 10% on friendly targets at or below 50% health."
							
						]
					}
					,
					{
						id:     2235,
						tier:   7,
						column: 0,
						name:  "Renewed Hope",
						icon:  "spell_holy_holyprotection",
						
						ranks: [
						
							"Increases the critical effect chance of your Flash Heal, Greater Heal and Penance (Heal) spells by 2% on targets afflicted by the Weakened Soul effect, and you have a 50% chance to reduce all damage taken by 3% for 20 sec to all friendly party and raid targets when you cast Power Word: Shield."
							,
							"Increases the critical effect chance of your Flash Heal, Greater Heal and Penance (Heal) spells by 4% on targets afflicted by the Weakened Soul effect, and you have a 100% chance to reduce all damage taken by 3% for 20 sec to all friendly party and raid targets when you cast Power Word: Shield."
							
						]
					}
					,
					{
						id:     1896,
						tier:   7,
						column: 1,
						name:  "Rapture",
						icon:  "spell_holy_rapture",
						
						ranks: [
						
							"When your Power Word: Shield is completely absorbed or dispelled you are instantly energized with 1.5% of your total mana, and you have a 33% chance to energize your shielded target with 2% total mana, 8 rage, 16 energy or 32 runic power. This effect can only occur once every 12 sec."
							,
							"When your Power Word: Shield is completely absorbed or dispelled you are instantly energized with 2% of your total mana, and you have a 66% chance to energize your shielded target with 2% total mana, 8 rage, 16 energy or 32 runic power. This effect can only occur once every 12 sec."
							,
							"When your Power Word: Shield is completely absorbed or dispelled you are instantly energized with 2.5% of your total mana, and you have a 100% chance to energize your shielded target with 2% total mana, 8 rage, 16 energy or 32 runic power. This effect can only occur once every 12 sec."
							
						]
					}
					,
					{
						id:     1894,
						tier:   7,
						column: 2,
						name:  "Aspiration",
						icon:  "spell_holy_aspiration",
						
						ranks: [
						
							"Reduces the cooldown of your Inner Focus, Power Infusion, Pain Suppression and Penance spells by 10%."
							,
							"Reduces the cooldown of your Inner Focus, Power Infusion, Pain Suppression and Penance spells by 20%."
							
						]
					}
					,
					{
						id:     1895,
						tier:   8,
						column: 0,
						name:  "Divine Aegis",
						icon:  "spell_holy_devineaegis",
						
						ranks: [
						
							"Critical heals create a protective shield on the target, absorbing 10% of the amount healed. Lasts 12 sec."
							,
							"Critical heals create a protective shield on the target, absorbing 20% of the amount healed. Lasts 12 sec."
							,
							"Critical heals create a protective shield on the target, absorbing 30% of the amount healed. Lasts 12 sec."
							
						]
					}
					,
					{
						id:     1774,
						tier:   8,
						column: 1,
						name:  "Pain Suppression",
						icon:  "spell_holy_painsupression",
						
						ranks: [
						
							"Instantly reduces a friendly target's threat by 5%, reduces all damage taken by 40% and increases resistance to Dispel mechanics by 65% for 8 sec."
							
						]
					}
					,
					{
						id:     1901,
						tier:   8,
						column: 2,
						name:  "Grace",
						icon:  "spell_holy_hopeandgrace",
						
						ranks: [
						
							"Your Flash Heal, Greater Heal, and Penance spells have a 50% chance to bless the target with Grace, increasing all healing received from the Priest by 3%. This effect will stack up to 3 times. Effect lasts 15 sec. Grace can only be active on one target at a time."
							,
							"Your Flash Heal, Greater Heal, and Penance spells have a 100% chance to bless the target with Grace, increasing all healing received from the Priest by 3%. This effect will stack up to 3 times. Effect lasts 15 sec. Grace can only be active on one target at a time."
							
						]
					}
					,
					{
						id:     1202,
						tier:   9,
						column: 1,
						name:  "Borrowed Time",
						icon:  "spell_holy_borrowedtime",
						
						ranks: [
						
							"Grants 5% spell haste for your next spell after casting Power Word: Shield, and increases the amount absorbed by your Power Word: Shield equal to 8% of your spell power."
							,
							"Grants 10% spell haste for your next spell after casting Power Word: Shield, and increases the amount absorbed by your Power Word: Shield equal to 16% of your spell power."
							,
							"Grants 15% spell haste for your next spell after casting Power Word: Shield, and increases the amount absorbed by your Power Word: Shield equal to 24% of your spell power."
							,
							"Grants 20% spell haste for your next spell after casting Power Word: Shield, and increases the amount absorbed by your Power Word: Shield equal to 32% of your spell power."
							,
							"Grants 25% spell haste for your next spell after casting Power Word: Shield, and increases the amount absorbed by your Power Word: Shield equal to 40% of your spell power."
							
						]
					}
					,
					{
						id:     1897,
						tier:   10,
						column: 1,
						name:  "Penance",
						icon:  "spell_holy_penance",
						
						ranks: [
						
							"Launches a volley of holy light at the target, causing 240 Holy damage to an enemy, or 670 to 756 healing to an ally instantly and every 1 sec for 2 sec."
							
						]
					}
					
				]
			}
			,
			{
				id:   "Holy",
				name: "Holy",
				talents: [
				
					{
						id:     410,
						tier:   0,
						column: 0,
						name:  "Healing Focus",
						icon:  "spell_holy_healingfocus",
						
						ranks: [
						
							"Reduces the pushback suffered from damaging attacks  while casting any healing spell by 35%."
							,
							"Reduces the pushback suffered from damaging attacks  while casting any healing spell by 70%."
							
						]
					}
					,
					{
						id:     406,
						tier:   0,
						column: 1,
						name:  "Improved Renew",
						icon:  "spell_holy_renew",
						
						ranks: [
						
							"Increases the amount healed by your Renew spell by 5%."
							,
							"Increases the amount healed by your Renew spell by 10%."
							,
							"Increases the amount healed by your Renew spell by 15%."
							
						]
					}
					,
					{
						id:     401,
						tier:   0,
						column: 2,
						name:  "Holy Specialization",
						icon:  "spell_holy_sealofsalvation",
						
						ranks: [
						
							"Increases the critical effect chance of your Holy spells by 1%."
							,
							"Increases the critical effect chance of your Holy spells by 2%."
							,
							"Increases the critical effect chance of your Holy spells by 3%."
							,
							"Increases the critical effect chance of your Holy spells by 4%."
							,
							"Increases the critical effect chance of your Holy spells by 5%."
							
						]
					}
					,
					{
						id:     411,
						tier:   1,
						column: 1,
						name:  "Spell Warding",
						icon:  "spell_holy_spellwarding",
						
						ranks: [
						
							"Reduces all spell damage taken by 2%."
							,
							"Reduces all spell damage taken by 4%."
							,
							"Reduces all spell damage taken by 6%."
							,
							"Reduces all spell damage taken by 8%."
							,
							"Reduces all spell damage taken by 10%."
							
						]
					}
					,
					{
						id:     1181,
						tier:   1,
						column: 2,
						name:  "Divine Fury",
						icon:  "spell_holy_sealofwrath",
						
						ranks: [
						
							"Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.1 sec."
							,
							"Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.2 sec."
							,
							"Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.3 sec."
							,
							"Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.4 sec."
							,
							"Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.5 sec."
							
						]
					}
					,
					{
						id:     442,
						tier:   2,
						column: 0,
						name:  "Desperate Prayer",
						icon:  "spell_holy_restoration",
						
						ranks: [
						
							"Instantly heals the caster for 263 to 325."
							
						]
					}
					,
					{
						id:     1636,
						tier:   2,
						column: 1,
						name:  "Blessed Recovery",
						icon:  "spell_holy_blessedrecovery",
						
						ranks: [
						
							"After being struck by a melee or ranged critical hit, Blessed Recovery heals you for 5% of the damage taken over 6 sec.  Additional critical hits taken during the effect increase the healing received."
							,
							"After being struck by a melee or ranged critical hit, Blessed Recovery heals you for 10% of the damage taken over 6 sec.  Additional critical hits taken during the effect increase the healing received."
							,
							"After being struck by a melee or ranged critical hit, Blessed Recovery heals you for 15% of the damage taken over 6 sec.  Additional critical hits taken during the effect increase the healing received."
							
						]
					}
					,
					{
						id:     361,
						tier:   2,
						column: 3,
						name:  "Inspiration",
						icon:  "spell_holy_layonhands",
						
						ranks: [
						
							"Reduces your target's physical damage taken by 3% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, Binding Heal, Penance, Prayer of Mending, Prayer of Healing, or Circle of Healing spell."
							,
							"Reduces your target's physical damage taken by 7% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, Binding Heal, Penance, Prayer of Mending, Prayer of Healing, or Circle of Healing spell."
							,
							"Reduces your target's physical damage taken by 10% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, Binding Heal, Penance, Prayer of Mending, Prayer of Healing, or Circle of Healing spell."
							
						]
					}
					,
					{
						id:     1635,
						tier:   3,
						column: 0,
						name:  "Holy Reach",
						icon:  "spell_holy_purify",
						
						ranks: [
						
							"Increases the range of your Smite and Holy Fire spells and the radius of your Prayer of Healing, Holy Nova, Divine Hymn and Circle of Healing spells by 10%."
							,
							"Increases the range of your Smite and Holy Fire spells and the radius of your Prayer of Healing, Holy Nova, Divine Hymn and Circle of Healing spells by 20%."
							
						]
					}
					,
					{
						id:     408,
						tier:   3,
						column: 1,
						name:  "Improved Healing",
						icon:  "spell_holy_heal02",
						
						ranks: [
						
							"Reduces the mana cost of your Lesser Heal, Heal, Greater Heal, Divine Hymn and Penance spells by 5%."
							,
							"Reduces the mana cost of your Lesser Heal, Heal, Greater Heal, Divine Hymn and Penance spells by 10%."
							,
							"Reduces the mana cost of your Lesser Heal, Heal, Greater Heal, Divine Hymn and Penance spells by 15%."
							
						]
					}
					,
					{
						id:     403,
						tier:   3,
						column: 2,
						name:  "Searing Light",
						icon:  "spell_holy_searinglightpriest",
						
							requires: 1181,
						
						ranks: [
						
							"Increases the damage of your Smite, Holy Fire, Holy Nova and Penance spells by 5%."
							,
							"Increases the damage of your Smite, Holy Fire, Holy Nova and Penance spells by 10%."
							
						]
					}
					,
					{
						id:     413,
						tier:   4,
						column: 0,
						name:  "Healing Prayers",
						icon:  "spell_holy_prayerofhealing02",
						
						ranks: [
						
							"Reduces the mana cost of your Prayer of Healing and Prayer of Mending spell by 10%."
							,
							"Reduces the mana cost of your Prayer of Healing and Prayer of Mending spell by 20%."
							
						]
					}
					,
					{
						id:     1561,
						tier:   4,
						column: 1,
						name:  "Spirit of Redemption",
						icon:  "inv_enchant_essenceeternallarge",
						
						ranks: [
						
							"Increases total Spirit by 5% and upon death, the priest becomes the Spirit of Redemption for 15 sec.  The Spirit of Redemption cannot move, attack, be attacked or targeted by any spells or effects.  While in this form the priest can cast any healing spell free of cost.  When the effect ends, the priest dies."
							
						]
					}
					,
					{
						id:     402,
						tier:   4,
						column: 2,
						name:  "Spiritual Guidance",
						icon:  "spell_holy_spiritualguidence",
						
						ranks: [
						
							"Increases spell power by 5% of your total Spirit."
							,
							"Increases spell power by 10% of your total Spirit."
							,
							"Increases spell power by 15% of your total Spirit."
							,
							"Increases spell power by 20% of your total Spirit."
							,
							"Increases spell power by 25% of your total Spirit."
							
						]
					}
					,
					{
						id:     1766,
						tier:   5,
						column: 0,
						name:  "Surge of Light",
						icon:  "spell_holy_surgeoflight",
						
						ranks: [
						
							"Your spell criticals have a 25% chance to cause your next Smite or Flash Heal spell to be instant cast, cost no mana but be incapable of a critical hit.  This effect lasts 10 sec."
							,
							"Your spell criticals have a 50% chance to cause your next Smite or Flash Heal spell to be instant cast, cost no mana but be incapable of a critical hit.  This effect lasts 10 sec."
							
						]
					}
					,
					{
						id:     404,
						tier:   5,
						column: 2,
						name:  "Spiritual Healing",
						icon:  "spell_nature_moonglow",
						
						ranks: [
						
							"Increases the amount healed by your healing spells by 2%."
							,
							"Increases the amount healed by your healing spells by 4%."
							,
							"Increases the amount healed by your healing spells by 6%."
							,
							"Increases the amount healed by your healing spells by 8%."
							,
							"Increases the amount healed by your healing spells by 10%."
							
						]
					}
					,
					{
						id:     1768,
						tier:   6,
						column: 0,
						name:  "Holy Concentration",
						icon:  "spell_holy_fanaticism",
						
						ranks: [
						
							"Your mana regeneration from spirit is increased by 16% for 8 sec after you critically heal with Flash Heal, Greater Heal, Binding Heal or Empowered Renew."
							,
							"Your mana regeneration from spirit is increased by 32% for 8 sec after you critically heal with Flash Heal, Greater Heal, Binding Heal or Empowered Renew."
							,
							"Your mana regeneration from spirit is increased by 50% for 8 sec after you critically heal with Flash Heal, Greater Heal, Binding Heal or Empowered Renew."
							
						]
					}
					,
					{
						id:     1637,
						tier:   6,
						column: 1,
						name:  "Lightwell",
						icon:  "spell_holy_summonlightwell",
						
							requires: 1561,
						
						ranks: [
						
							"Creates a Holy Lightwell.  Members of your raid or party can click the Lightwell to restore 801 health over 6 sec.  Attacks done to you equal to 30% of your total health will cancel the effect. Lightwell lasts for 3 min or 10 charges."
							
						]
					}
					,
					{
						id:     1765,
						tier:   6,
						column: 2,
						name:  "Blessed Resilience",
						icon:  "spell_holy_blessedresillience",
						
						ranks: [
						
							"Increases the effectiveness of your healing spells by 1%, and critical hits made against you have a 20% chance to prevent you from being critically hit again for 6 sec."
							,
							"Increases the effectiveness of your healing spells by 2%, and critical hits made against you have a 40% chance to prevent you from being critically hit again for 6 sec."
							,
							"Increases the effectiveness of your healing spells by 3%, and critical hits made against you have a 60% chance to prevent you from being critically hit again for 6 sec."
							
						]
					}
					,
					{
						id:     2279,
						tier:   7,
						column: 0,
						name:  "Body and Soul",
						icon:  "spell_holy_symbolofhope",
						
						ranks: [
						
							"When you cast Power Word: Shield, you increase the target's movement speed by 30% for 4 sec, and you have a 50% chance when you cast Abolish Disease on yourself to also cleanse 1 poison effect in addition to diseases."
							,
							"When you cast Power Word: Shield, you increase the target's movement speed by 60% for 4 sec, and you have a 100% chance when you cast Abolish Disease on yourself to also cleanse 1 poison effect in addition to diseases."
							
						]
					}
					,
					{
						id:     1767,
						tier:   7,
						column: 1,
						name:  "Empowered Healing",
						icon:  "spell_holy_greaterheal",
						
						ranks: [
						
							"Your Greater Heal spell gains an additional 8% and your Flash Heal and Binding Heal gain an additional 4% of your bonus healing effects."
							,
							"Your Greater Heal spell gains an additional 16% and your Flash Heal and Binding Heal gain an additional 8% of your bonus healing effects."
							,
							"Your Greater Heal spell gains an additional 24% and your Flash Heal and Binding Heal gain an additional 12% of your bonus healing effects."
							,
							"Your Greater Heal spell gains an additional 32% and your Flash Heal and Binding Heal gain an additional 16% of your bonus healing effects."
							,
							"Your Greater Heal spell gains an additional 40% and your Flash Heal and Binding Heal gain an additional 20% of your bonus healing effects."
							
						]
					}
					,
					{
						id:     1904,
						tier:   7,
						column: 2,
						name:  "Serendipity",
						icon:  "spell_holy_serendipity",
						
						ranks: [
						
							"When you heal with Binding Heal or Flash Heal, the cast time of your next Greater Heal or Prayer of Healing spell is reduced by 4%. Stacks up to 3 times. Lasts 20 sec."
							,
							"When you heal with Binding Heal or Flash Heal, the cast time of your next Greater Heal or Prayer of Healing spell is reduced by 8%. Stacks up to 3 times. Lasts 20 sec."
							,
							"When you heal with Binding Heal or Flash Heal, the cast time of your next Greater Heal or Prayer of Healing spell is reduced by 12%. Stacks up to 3 times. Lasts 20 sec."
							
						]
					}
					,
					{
						id:     1902,
						tier:   8,
						column: 0,
						name:  "Empowered Renew",
						icon:  "ability_paladin_infusionoflight",
						
						ranks: [
						
							"Your Renew spell gains an additional 5% of your bonus healing effects, and your Renew will instantly heal the target for 5% of the total periodic effect."
							,
							"Your Renew spell gains an additional 10% of your bonus healing effects, and your Renew will instantly heal the target for 10% of the total periodic effect."
							,
							"Your Renew spell gains an additional 15% of your bonus healing effects, and your Renew will instantly heal the target for 15% of the total periodic effect."
							
						]
					}
					,
					{
						id:     1815,
						tier:   8,
						column: 1,
						name:  "Circle of Healing",
						icon:  "spell_holy_circleofrenewal",
						
						ranks: [
						
							"Heals up to 5 friendly party or raid members within 15 yards of the target for 343 to 379."
							
						]
					}
					,
					{
						id:     1903,
						tier:   8,
						column: 2,
						name:  "Test of Faith",
						icon:  "spell_holy_testoffaith",
						
						ranks: [
						
							"Increases healing by 4% on friendly targets at or below 50% health."
							,
							"Increases healing by 8% on friendly targets at or below 50% health."
							,
							"Increases healing by 12% on friendly targets at or below 50% health."
							
						]
					}
					,
					{
						id:     1905,
						tier:   9,
						column: 1,
						name:  "Divine Providence",
						icon:  "spell_holy_divineprovidence",
						
						ranks: [
						
							"Increases the amount healed by Circle of Healing, Binding Heal, Holy Nova, Prayer of Healing, Divine Hymn and Prayer of Mending by 2%, and reduces the cooldown of your Prayer of Mending by 6%."
							,
							"Increases the amount healed by Circle of Healing, Binding Heal, Holy Nova, Prayer of Healing, Divine Hymn and Prayer of Mending by 4%, and reduces the cooldown of your Prayer of Mending by 12%."
							,
							"Increases the amount healed by Circle of Healing, Binding Heal, Holy Nova, Prayer of Healing, Divine Hymn and Prayer of Mending by 6%, and reduces the cooldown of your Prayer of Mending by 18%."
							,
							"Increases the amount healed by Circle of Healing, Binding Heal, Holy Nova, Prayer of Healing, Divine Hymn and Prayer of Mending by 8%, and reduces the cooldown of your Prayer of Mending by 24%."
							,
							"Increases the amount healed by Circle of Healing, Binding Heal, Holy Nova, Prayer of Healing, Divine Hymn and Prayer of Mending by 10%, and reduces the cooldown of your Prayer of Mending by 30%."
							
						]
					}
					,
					{
						id:     1911,
						tier:   10,
						column: 1,
						name:  "Guardian Spirit",
						icon:  "spell_holy_guardianspirit",
						
						ranks: [
						
							"Calls upon a guardian spirit to watch over the friendly target. The spirit increases the healing received by the target by 40%, and also prevents the target from dying by sacrificing itself.  This sacrifice terminates the effect but heals the target of 50% of their maximum health. Lasts 10 sec."
							
						]
					}
					
				]
			}
			,
			{
				id:   "Shadow",
				name: "Shadow",
				talents: [
				
					{
						id:     465,
						tier:   0,
						column: 0,
						name:  "Spirit Tap",
						icon:  "spell_shadow_requiem",
						
						ranks: [
						
							"Gives you a 33% chance to gain a 100% bonus to your Spirit after killing a target that yields experience or honor.  For the duration, your mana will regenerate at a 83% rate while casting.  Lasts 15 sec."
							,
							"Gives you a 66% chance to gain a 100% bonus to your Spirit after killing a target that yields experience or honor.  For the duration, your mana will regenerate at a 83% rate while casting.  Lasts 15 sec."
							,
							"Gives you a 100% chance to gain a 100% bonus to your Spirit after killing a target that yields experience or honor.  For the duration, your mana will regenerate at a 83% rate while casting.  Lasts 15 sec."
							
						]
					}
					,
					{
						id:     2027,
						tier:   0,
						column: 1,
						name:  "Improved Spirit Tap",
						icon:  "spell_shadow_requiem",
						
							requires: 465,
						
						ranks: [
						
							"Your Mind Blast and Shadow Word: Death critical strikes have a 100% chance and your Mind Flay critical strikes have a 50% chance to increase your total Spirit by 5%. For the duration, your mana will regenerate at a 17% rate while casting. Lasts 8 sec."
							,
							"Your Mind Blast and Shadow Word: Death critical strikes have a 100% chance and your Mind Flay critical strikes have a 50% chance to increase your total Spirit by 10%. For the duration, your mana will regenerate at a 33% rate while casting. Lasts 8 sec."
							
						]
					}
					,
					{
						id:     462,
						tier:   0,
						column: 2,
						name:  "Darkness",
						icon:  "spell_shadow_twilight",
						
						ranks: [
						
							"Increases your Shadow spell damage by 2%."
							,
							"Increases your Shadow spell damage by 4%."
							,
							"Increases your Shadow spell damage by 6%."
							,
							"Increases your Shadow spell damage by 8%."
							,
							"Increases your Shadow spell damage by 10%."
							
						]
					}
					,
					{
						id:     466,
						tier:   1,
						column: 0,
						name:  "Shadow Affinity",
						icon:  "spell_shadow_shadowward",
						
						ranks: [
						
							"Reduces the threat generated by your Shadow spells by 8%, and you receive 5% of your base mana when your Shadow Word: Pain or Vampiric Touch spells are dispelled."
							,
							"Reduces the threat generated by your Shadow spells by 16%, and you receive 10% of your base mana when your Shadow Word: Pain or Vampiric Touch spells are dispelled."
							,
							"Reduces the threat generated by your Shadow spells by 25%, and you receive 15% of your base mana when your Shadow Word: Pain or Vampiric Touch spells are dispelled."
							
						]
					}
					,
					{
						id:     482,
						tier:   1,
						column: 1,
						name:  "Improved Shadow Word: Pain",
						icon:  "spell_shadow_shadowwordpain",
						
						ranks: [
						
							"Increases the damage of your Shadow Word: Pain spell by 3%."
							,
							"Increases the damage of your Shadow Word: Pain spell by 6%."
							
						]
					}
					,
					{
						id:     463,
						tier:   1,
						column: 2,
						name:  "Shadow Focus",
						icon:  "spell_shadow_burningspirit",
						
						ranks: [
						
							"Increases your chance to hit with your Shadow spells by 1%, and reduces the mana cost of your Shadow spells by 2%."
							,
							"Increases your chance to hit with your Shadow spells by 2%, and reduces the mana cost of your Shadow spells by 4%."
							,
							"Increases your chance to hit with your Shadow spells by 3%, and reduces the mana cost of your Shadow spells by 6%."
							
						]
					}
					,
					{
						id:     542,
						tier:   2,
						column: 0,
						name:  "Improved Psychic Scream",
						icon:  "spell_shadow_psychicscream",
						
						ranks: [
						
							"Reduces the cooldown of your Psychic Scream spell by 2 sec."
							,
							"Reduces the cooldown of your Psychic Scream spell by 4 sec."
							
						]
					}
					,
					{
						id:     481,
						tier:   2,
						column: 1,
						name:  "Improved Mind Blast",
						icon:  "spell_shadow_unholyfrenzy",
						
						ranks: [
						
							"Reduces the cooldown of your Mind Blast spell by 0.5 sec., and while in Shadowform your Mind Blast also has a 20% chance to reduce all healing done to the target by 20% for 10 sec."
							,
							"Reduces the cooldown of your Mind Blast spell by 1 sec., and while in Shadowform your Mind Blast also has a 40% chance to reduce all healing done to the target by 20% for 10 sec."
							,
							"Reduces the cooldown of your Mind Blast spell by 1.5 sec., and while in Shadowform your Mind Blast also has a 60% chance to reduce all healing done to the target by 20% for 10 sec."
							,
							"Reduces the cooldown of your Mind Blast spell by 2 sec., and while in Shadowform your Mind Blast also has a 80% chance to reduce all healing done to the target by 20% for 10 sec."
							,
							"Reduces the cooldown of your Mind Blast spell by 2.5 sec., and while in Shadowform your Mind Blast also has a 100% chance to reduce all healing done to the target by 20% for 10 sec."
							
						]
					}
					,
					{
						id:     501,
						tier:   2,
						column: 2,
						name:  "Mind Flay",
						icon:  "spell_shadow_siphonmana",
						
						ranks: [
						
							"Assault the target's mind with Shadow energy, causing 45 Shadow damage over 3 sec and slowing their movement speed by 50%."
							
						]
					}
					,
					{
						id:     483,
						tier:   3,
						column: 1,
						name:  "Veiled Shadows",
						icon:  "spell_magic_lesserinvisibilty",
						
						ranks: [
						
							"Decreases the cooldown of your Fade ability by 3 sec, and reduces the cooldown of your Shadowfiend ability by 1 minute."
							,
							"Decreases the cooldown of your Fade ability by 6 sec, and reduces the cooldown of your Shadowfiend ability by 2 minutes."
							
						]
					}
					,
					{
						id:     881,
						tier:   3,
						column: 2,
						name:  "Shadow Reach",
						icon:  "spell_shadow_chilltouch",
						
						ranks: [
						
							"Increases the range of your offensive Shadow spells by 10%."
							,
							"Increases the range of your offensive Shadow spells by 20%."
							
						]
					}
					,
					{
						id:     461,
						tier:   3,
						column: 3,
						name:  "Shadow Weaving",
						icon:  "spell_shadow_blackplague",
						
						ranks: [
						
							"Your Shadow damage spells have a 33% chance to increase the Shadow damage you deal by 2% for 15 sec.  Stacks up to 5 times."
							,
							"Your Shadow damage spells have a 66% chance to increase the Shadow damage you deal by 2% for 15 sec.  Stacks up to 5 times."
							,
							"Your Shadow damage spells have a 100% chance to increase the Shadow damage you deal by 2% for 15 sec.  Stacks up to 5 times."
							
						]
					}
					,
					{
						id:     541,
						tier:   4,
						column: 0,
						name:  "Silence",
						icon:  "spell_shadow_impphaseshift",
						
							requires: 542,
						
						ranks: [
						
							"Silences the target, preventing them from casting spells for 5 sec.  Non-player victim spellcasting is also interrupted for 3 sec."
							
						]
					}
					,
					{
						id:     484,
						tier:   4,
						column: 1,
						name:  "Vampiric Embrace",
						icon:  "spell_shadow_unsummonbuilding",
						
						ranks: [
						
							"Fills you with the embrace of Shadow energy, causing you to be healed for 15% and other party members to be healed for 3% of any single-target Shadow spell damage you deal for 30 min."
							
						]
					}
					,
					{
						id:     1638,
						tier:   4,
						column: 2,
						name:  "Improved Vampiric Embrace",
						icon:  "spell_shadow_improvedvampiricembrace",
						
							requires: 484,
						
						ranks: [
						
							"Increases the healing received from Vampiric Embrace by 33%."
							,
							"Increases the healing received from Vampiric Embrace by 67%."
							
						]
					}
					,
					{
						id:     1777,
						tier:   4,
						column: 3,
						name:  "Focused Mind",
						icon:  "spell_nature_focusedmind",
						
						ranks: [
						
							"Reduces the mana cost of your Mind Blast, Mind Control, Mind Flay and Mind Sear spells by 5%."
							,
							"Reduces the mana cost of your Mind Blast, Mind Control, Mind Flay and Mind Sear spells by 10%."
							,
							"Reduces the mana cost of your Mind Blast, Mind Control, Mind Flay and Mind Sear spells by 15%."
							
						]
					}
					,
					{
						id:     1781,
						tier:   5,
						column: 0,
						name:  "Mind Melt",
						icon:  "spell_shadow_skull",
						
						ranks: [
						
							"Increases the critical strike chance of your Mind Blast, Mind Flay and Mind Sear spells by 2%, and increases the periodic critical strike chance of your Vampiric Touch, Devouring Plague and Shadow Word: Pain spells by 3%."
							,
							"Increases the critical strike chance of your Mind Blast, Mind Flay and Mind Sear spells by 4%, and increases the periodic critical strike chance of your Vampiric Touch, Devouring Plague and Shadow Word: Pain spells by 6%."
							
						]
					}
					,
					{
						id:     2267,
						tier:   5,
						column: 2,
						name:  "Improved Devouring Plague",
						icon:  "spell_shadow_devouringplague.",
						
						ranks: [
						
							"Increases the periodic damage done by your Devouring Plague by 5%, and when you cast Devouring Plague you instantly deal damage equal to 10% of its total periodic effect."
							,
							"Increases the periodic damage done by your Devouring Plague by 10%, and when you cast Devouring Plague you instantly deal damage equal to 20% of its total periodic effect."
							,
							"Increases the periodic damage done by your Devouring Plague by 15%, and when you cast Devouring Plague you instantly deal damage equal to 30% of its total periodic effect."
							
						]
					}
					,
					{
						id:     521,
						tier:   6,
						column: 1,
						name:  "Shadowform",
						icon:  "spell_shadow_shadowform",
						
							requires: 484,
						
						ranks: [
						
							"Assume a Shadowform, increasing your Shadow damage by 15%, reducing all damage done to you by 15% and threat generated by 30%.  However, you may not cast Holy spells while in this form except Cure Disease and Abolish Disease.  Grants the periodic damage from your Shadow Word: Pain, Devouring Plague, and Vampiric Touch spells the ability to critically hit for 100% increased damage and grants Devouring Plague and Vampiric Touch the ability to benefit from haste."
							
						]
					}
					,
					{
						id:     1778,
						tier:   6,
						column: 2,
						name:  "Shadow Power",
						icon:  "spell_shadow_shadowpower",
						
						ranks: [
						
							"Increases the critical strike damage bonus of your Mind Blast, Mind Flay, and Shadow Word: Death spells by 20%."
							,
							"Increases the critical strike damage bonus of your Mind Blast, Mind Flay, and Shadow Word: Death spells by 40%."
							,
							"Increases the critical strike damage bonus of your Mind Blast, Mind Flay, and Shadow Word: Death spells by 60%."
							,
							"Increases the critical strike damage bonus of your Mind Blast, Mind Flay, and Shadow Word: Death spells by 80%."
							,
							"Increases the critical strike damage bonus of your Mind Blast, Mind Flay, and Shadow Word: Death spells by 100%."
							
						]
					}
					,
					{
						id:     1906,
						tier:   7,
						column: 0,
						name:  "Improved Shadowform",
						icon:  "spell_shadow_summonvoidwalker",
						
							requires: 521,
						
						ranks: [
						
							"Your Fade ability now has a 50% chance to remove all movement impairing effects when used while in Shadowform, and reduces casting or channeling time lost when damaged by 35% when casting any Shadow spell while in Shadowform."
							,
							"Your Fade ability now has a 100% chance to remove all movement impairing effects when used while in Shadowform, and reduces casting or channeling time lost when damaged by 70% when casting any Shadow spell while in Shadowform."
							
						]
					}
					,
					{
						id:     1816,
						tier:   7,
						column: 2,
						name:  "Misery",
						icon:  "spell_shadow_misery",
						
						ranks: [
						
							"Your Shadow Word: Pain, Mind Flay and Vampiric Touch spells also increase the chance for harmful spells to hit by 1% lasting 24 sec, and increases the benefit from spell power gained by your Mind Blast, Mind Flay and Mind Sear spells by 5%."
							,
							"Your Shadow Word: Pain, Mind Flay and Vampiric Touch spells also increase the chance for harmful spells to hit by 2% lasting 24 sec, and increases the benefit from spell power gained by your Mind Blast, Mind Flay and Mind Sear spells by 10%."
							,
							"Your Shadow Word: Pain, Mind Flay and Vampiric Touch spells also increase the chance for harmful spells to hit by 3% lasting 24 sec, and increases the benefit from spell power gained by your Mind Blast, Mind Flay and Mind Sear spells by 15%."
							
						]
					}
					,
					{
						id:     1908,
						tier:   8,
						column: 0,
						name:  "Psychic Horror",
						icon:  "spell_shadow_psychichorrors",
						
						ranks: [
						
							"You terrify the target, causing them to tremble in horror for 3 sec and drop their main hand and ranged weapons for 10 sec."
							
						]
					}
					,
					{
						id:     1779,
						tier:   8,
						column: 1,
						name:  "Vampiric Touch",
						icon:  "spell_holy_stoicism",
						
							requires: 521,
						
						ranks: [
						
							"Causes 450 Shadow damage over 15 sec to your target and causes up to 10 party or raid members to gain 1% of their maximum mana per 5 sec when you deal damage from Mind Blast. In addition, if the Vampiric Touch is dispelled it will cause 720 damage to the afflicted target."
							
						]
					}
					,
					{
						id:     1909,
						tier:   8,
						column: 2,
						name:  "Pain and Suffering",
						icon:  "spell_shadow_painandsuffering",
						
						ranks: [
						
							"Your Mind Flay has a 33% chance to refresh the duration of your Shadow Word: Pain on the target, and reduces the damage you take from your own Shadow Word: Death by 10%."
							,
							"Your Mind Flay has a 66% chance to refresh the duration of your Shadow Word: Pain on the target, and reduces the damage you take from your own Shadow Word: Death by 20%."
							,
							"Your Mind Flay has a 100% chance to refresh the duration of your Shadow Word: Pain on the target, and reduces the damage you take from your own Shadow Word: Death by 30%."
							
						]
					}
					,
					{
						id:     1907,
						tier:   9,
						column: 2,
						name:  "Twisted Faith",
						icon:  "spell_shadow_mindtwisting",
						
						ranks: [
						
							"Increases your spell power by 4% of your total Spirit, and your damage done by your Mind Flay and Mind Blast is increased by 2% if your target is afflicted by your Shadow Word: Pain."
							,
							"Increases your spell power by 8% of your total Spirit, and your damage done by your Mind Flay and Mind Blast is increased by 4% if your target is afflicted by your Shadow Word: Pain."
							,
							"Increases your spell power by 12% of your total Spirit, and your damage done by your Mind Flay and Mind Blast is increased by 6% if your target is afflicted by your Shadow Word: Pain."
							,
							"Increases your spell power by 16% of your total Spirit, and your damage done by your Mind Flay and Mind Blast is increased by 8% if your target is afflicted by your Shadow Word: Pain."
							,
							"Increases your spell power by 20% of your total Spirit, and your damage done by your Mind Flay and Mind Blast is increased by 10% if your target is afflicted by your Shadow Word: Pain."
							
						]
					}
					,
					{
						id:     1910,
						tier:   10,
						column: 1,
						name:  "Dispersion",
						icon:  "spell_shadow_dispersion",
						
							requires: 1779,
						
						ranks: [
						
							"You disperse into pure Shadow energy, reducing all damage taken by 90%.  You are unable to attack or cast spells, but you regenerate 6% mana every 1 sec for 6 sec. Dispersion can be cast while stunned, feared or silenced and clears all snare and movement impairing effects when cast, and makes you immune to them while dispersed."
							
						]
					}
					
				]
			}
			
		];

		var petData_sdfkte75 = null;
		
	
		var textTalentStrSingle = "Requires {0} point in {1}.";
		var textTalentStrPlural = "Requires {0} points in {1}.";
		var textTalentRank = "Rank {0}/{1}";
		var textTalentNextRank = "Next Rank";
		var textTalentReqTreeTalents = "Requires {0} points in {1} Talents.";
		var textPrintableClassTalents = "{0} Talents";
		var textPrintableMinReqLevel = "Minimum Required Level: {0}";
		var textPrintableReqTalentPts = "Required Talent Points: {0}";
		var textPrintableTreeTalents = "{0} Talents";
		var textPrintablePtsPerTree = "{0} point(s)";
		var textPrintableDontWastePaper = "Don't waste paper!";

		var talentCalc = new TalentCalculator();

		$(document).ready(function() {

			talentCalc.initTalentCalc(
				"5", 
				"{{$talents}}", 
				"charPage",
				"false",
				"sdfkte75",
				talentData_sdfkte75,
				petData_sdfkte75
			);
		});
	</script>
<div class="talContainer" id="talContainer_sdfkte75">
<div class="talentFrame">
<div class="talentTree" id="Discipline_tree_sdfkte75" style="margin-right: 3px; background-image: url('images/talents/bg/small/PriestDiscipline.jpg')">
<div class="tier">
<div class="talent staticTip col1" id="342_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/spell_magic_magearmor.jpg');">
<div class="talentHolder
						" id="342_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(342);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="342_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1898_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/spell_holy_sealofvengeance.jpg');">
<div class="talentHolder
						" id="1898_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1898);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1898_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="352_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_nature_manaregentotem.jpg');">
<div class="talentHolder
						 disabled" id="352_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(352);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="352_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="346_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_innerfire.jpg');">
<div class="talentHolder
						 disabled" id="346_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(346);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="346_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="344_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_wordfortitude.jpg');">
<div class="talentHolder
						 disabled" id="344_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(344);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="344_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col3" id="321_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_nature_tranquility.jpg');">
<div class="talentHolder
						 disabled" id="321_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(321);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="321_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="347_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_nature_sleep.jpg');">
<div class="talentHolder
						 disabled" id="347_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(347);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="347_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="348_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_frost_windwalkon.jpg');">
<div class="talentHolder
						 disabled" id="348_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(348);">
<span id="spellInfo_348" style="display: none;"><span style="float: right;">3 min cooldown</span><span style="float: left;">Instant</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="348_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="343_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_powerwordshield.jpg');">
<div class="talentHolder
						 disabled" id="343_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(343);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="343_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="1769_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_absolution.jpg');">
<div class="talentHolder
						 disabled" id="1769_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1769);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1769_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="341_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_hibernation.jpg');">
<div class="talentHolder
						 disabled" id="341_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(341);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="341_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col3" id="350_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_manaburn.jpg');">
<div class="talentHolder
						 disabled" id="350_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(350);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="350_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="2268_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_powerwordshield.jpg');">
<div class="talentHolder
						 disabled" id="2268_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(2268);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="2268_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="1201_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_nature_enchantarmor.jpg');">
<div class="talentHolder
						 disabled" id="1201_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1201);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1201_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="351_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_pureofheart.jpg');">
<div class="talentHolder
						 disabled" id="351_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(351);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="351_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="1771_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_focusedpower.jpg');">
<div class="talentHolder
						 disabled" id="1771_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1771);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1771_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1772_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_arcane_mindmastery.jpg');">
<div class="talentHolder
						 disabled" id="1772_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1772);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1772_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="1858_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_arcane_focusedpower.jpg');">
<div class="talentHolder
						 disabled" id="1858_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1858);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1858_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="322_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_powerinfusion.jpg');">
<div class="talentHolder
						 disabled" id="322_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(322);">
<span id="spellInfo_322" style="display: none;"><span style="float: right;">30 yd range</span><span style="float: left;">16% of base mana</span>
<br>
<span style="float: right;">2 min cooldown</span><span style="float: left;">Instant cast</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="322_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1773_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_chastise.jpg');">
<div class="talentHolder
						 disabled" id="1773_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1773);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1773_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="2235_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_holyprotection.jpg');">
<div class="talentHolder
						 disabled" id="2235_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(2235);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="2235_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="1896_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_rapture.jpg');">
<div class="talentHolder
						 disabled" id="1896_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1896);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1896_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1894_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_aspiration.jpg');">
<div class="talentHolder
						 disabled" id="1894_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1894);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1894_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="1895_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_devineaegis.jpg');">
<div class="talentHolder
						 disabled" id="1895_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1895);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1895_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="1774_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_painsupression.jpg');">
<div class="talentHolder
						 disabled" id="1774_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1774);">
<span id="spellInfo_1774" style="display: none;"><span style="float: right;">40 yd range</span><span style="float: left;">8% of base mana</span>
<br>
<span style="float: right;">3 min cooldown</span><span style="float: left;">Instant cast</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1774_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1901_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_hopeandgrace.jpg');">
<div class="talentHolder
						 disabled" id="1901_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1901);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1901_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col1" id="1202_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_borrowedtime.jpg');">
<div class="talentHolder
						 disabled" id="1202_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1202);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1202_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col1" id="1897_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_penance.jpg');">
<div class="talentHolder
						 disabled" id="1897_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1897);">
<span id="spellInfo_1897" style="display: none;"><span style="float: right;">30 yd range</span><span style="float: left;">16% of base mana</span>
<br>
<span style="float: right;">12 sec cooldown</span><span style="float: left;">Channeled</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1897_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
</div>
<div class="talentTreeInfo" style="background: url(wow-icons/_images/21x21/spell_holy_wordfortitude.png) 0 0 no-repeat;">
<span id="treeName_0_sdfkte75" style="font-weight: bold;">Discipline</span> &nbsp;<span id="treeSpent_0_sdfkte75">0</span>
</div>
</div>
<div class="talentTree" id="Holy_tree_sdfkte75" style="margin-right: 3px; background-image: url('images/talents/bg/small/PriestHoly.jpg')">
<div class="tier">
<div class="talent staticTip col0" id="410_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/spell_holy_healingfocus.jpg');">
<div class="talentHolder
						" id="410_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(410);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="410_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="406_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/spell_holy_renew.jpg');">
<div class="talentHolder
						" id="406_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(406);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="406_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="401_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/spell_holy_sealofsalvation.jpg');">
<div class="talentHolder
						" id="401_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(401);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="401_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col1" id="411_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_spellwarding.jpg');">
<div class="talentHolder
						 disabled" id="411_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(411);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="411_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1181_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_sealofwrath.jpg');">
<div class="talentHolder
						 disabled" id="1181_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1181);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1181_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="442_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_restoration.jpg');">
<div class="talentHolder
						 disabled" id="442_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(442);">
<span id="spellInfo_442" style="display: none;"><span style="float: left;">21% of base mana</span>
<br>
<span style="float: right;">2 min cooldown</span><span style="float: left;">Instant cast</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="442_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="1636_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_blessedrecovery.jpg');">
<div class="talentHolder
						 disabled" id="1636_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1636);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1636_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col3" id="361_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_layonhands.jpg');">
<div class="talentHolder
						 disabled" id="361_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(361);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="361_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="1635_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_purify.jpg');">
<div class="talentHolder
						 disabled" id="1635_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1635);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1635_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="408_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_heal02.jpg');">
<div class="talentHolder
						 disabled" id="408_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(408);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="408_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="403_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_searinglightpriest.jpg');">
<div class="talentHolder
						 disabled" id="403_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(403);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="403_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="413_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_prayerofhealing02.jpg');">
<div class="talentHolder
						 disabled" id="413_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(413);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="413_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="1561_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/inv_enchant_essenceeternallarge.jpg');">
<div class="talentHolder
						 disabled" id="1561_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1561);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1561_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="402_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_spiritualguidence.jpg');">
<div class="talentHolder
						 disabled" id="402_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(402);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="402_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="1766_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_surgeoflight.jpg');">
<div class="talentHolder
						 disabled" id="1766_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1766);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1766_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="404_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_nature_moonglow.jpg');">
<div class="talentHolder
						 disabled" id="404_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(404);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="404_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="1768_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_fanaticism.jpg');">
<div class="talentHolder
						 disabled" id="1768_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1768);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1768_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="1637_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_summonlightwell.jpg');">
<div class="talentHolder
						 disabled" id="1637_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1637);">
<span id="spellInfo_1637" style="display: none;"><span style="float: right;">40 yd range</span><span style="float: left;">17% of base mana</span>
<br>
<span style="float: right;">3 min cooldown</span><span style="float: left;">0.5 sec cast</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1637_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1765_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_blessedresillience.jpg');">
<div class="talentHolder
						 disabled" id="1765_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1765);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1765_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="2279_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_symbolofhope.jpg');">
<div class="talentHolder
						 disabled" id="2279_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(2279);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="2279_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="1767_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_greaterheal.jpg');">
<div class="talentHolder
						 disabled" id="1767_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1767);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1767_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1904_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_serendipity.jpg');">
<div class="talentHolder
						 disabled" id="1904_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1904);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1904_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="1902_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_paladin_infusionoflight.jpg');">
<div class="talentHolder
						 disabled" id="1902_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1902);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1902_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="1815_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_circleofrenewal.jpg');">
<div class="talentHolder
						 disabled" id="1815_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1815);">
<span id="spellInfo_1815" style="display: none;"><span style="float: right;">40 yd range</span><span style="float: left;">21% of base mana</span>
<br>
<span style="float: right;">6 sec cooldown</span><span style="float: left;">Instant cast</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1815_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1903_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_testoffaith.jpg');">
<div class="talentHolder
						 disabled" id="1903_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1903);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1903_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col1" id="1905_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_divineprovidence.jpg');">
<div class="talentHolder
						 disabled" id="1905_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1905);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1905_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col1" id="1911_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_guardianspirit.jpg');">
<div class="talentHolder
						 disabled" id="1911_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1911);">
<span id="spellInfo_1911" style="display: none;"><span style="float: right;">40 yd range</span><span style="float: left;">6% of base mana</span>
<br>
<span style="float: right;">3 min cooldown</span><span style="float: left;">Instant cast</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1911_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
</div>
<div class="talentTreeInfo" style="background: url(wow-icons/_images/21x21/spell_holy_guardianspirit.png) 0 0 no-repeat;">
<span id="treeName_1_sdfkte75" style="font-weight: bold;">Holy</span> &nbsp;<span id="treeSpent_1_sdfkte75">0</span>
</div>
</div>
<div class="talentTree" id="Shadow_tree_sdfkte75" style="background-image: url('images/talents/bg/small/PriestShadow.jpg');">
<div class="tier">
<div class="talent staticTip col0" id="465_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/spell_shadow_requiem.jpg');">
<div class="talentHolder
						" id="465_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(465);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="465_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="2027_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/spell_shadow_requiem.jpg');">
<div class="talentHolder
						" id="2027_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(2027);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="2027_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="462_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/spell_shadow_twilight.jpg');">
<div class="talentHolder
						" id="462_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(462);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="462_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="466_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_shadowward.jpg');">
<div class="talentHolder
						 disabled" id="466_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(466);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="466_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="482_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_shadowwordpain.jpg');">
<div class="talentHolder
						 disabled" id="482_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(482);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="482_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="463_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_burningspirit.jpg');">
<div class="talentHolder
						 disabled" id="463_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(463);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="463_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="542_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_psychicscream.jpg');">
<div class="talentHolder
						 disabled" id="542_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(542);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="542_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="481_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_unholyfrenzy.jpg');">
<div class="talentHolder
						 disabled" id="481_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(481);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="481_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="501_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_siphonmana.jpg');">
<div class="talentHolder
						 disabled" id="501_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(501);">
<span id="spellInfo_501" style="display: none;"><span style="float: right;">30 yd range</span><span style="float: left;">9% of base mana</span>
<br>
<span style="float: left;">Channeled</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="501_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col1" id="483_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_magic_lesserinvisibilty.jpg');">
<div class="talentHolder
						 disabled" id="483_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(483);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="483_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="881_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_chilltouch.jpg');">
<div class="talentHolder
						 disabled" id="881_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(881);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="881_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col3" id="461_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_blackplague.jpg');">
<div class="talentHolder
						 disabled" id="461_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(461);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="461_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="541_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_impphaseshift.jpg');">
<div class="talentHolder
						 disabled" id="541_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(541);">
<span id="spellInfo_541" style="display: none;"><span style="float: right;">30 yd range</span><span style="float: left;">225 Mana</span>
<br>
<span style="float: right;">45 sec cooldown</span><span style="float: left;">Instant</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="541_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="484_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_unsummonbuilding.jpg');">
<div class="talentHolder
						 disabled" id="484_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(484);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="484_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1638_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_improvedvampiricembrace.jpg');">
<div class="talentHolder
						 disabled" id="1638_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1638);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1638_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col3" id="1777_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_nature_focusedmind.jpg');">
<div class="talentHolder
						 disabled" id="1777_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1777);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1777_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="1781_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_skull.jpg');">
<div class="talentHolder
						 disabled" id="1781_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1781);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1781_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="2267_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_devouringplague..jpg');">
<div class="talentHolder
						 disabled" id="2267_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(2267);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="2267_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col1" id="521_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_shadowform.jpg');">
<div class="talentHolder
						 disabled" id="521_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(521);">
<span id="spellInfo_521" style="display: none;"><span style="float: left;">13% of base mana</span>
<br>
<span style="float: right;">1.5 sec cooldown</span><span style="float: left;">Instant cast</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="521_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1778_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_shadowpower.jpg');">
<div class="talentHolder
						 disabled" id="1778_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1778);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1778_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="1906_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_summonvoidwalker.jpg');">
<div class="talentHolder
						 disabled" id="1906_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1906);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1906_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1816_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_misery.jpg');">
<div class="talentHolder
						 disabled" id="1816_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1816);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1816_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="1908_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_psychichorrors.jpg');">
<div class="talentHolder
						 disabled" id="1908_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1908);">
<span id="spellInfo_1908" style="display: none;"><span style="float: right;">30 yd range</span><span style="float: left;">16% of base mana</span>
<br>
<span style="float: right;">2 min cooldown</span><span style="float: left;">Instant cast</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1908_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="1779_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_stoicism.jpg');">
<div class="talentHolder
						 disabled" id="1779_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1779);">
<span id="spellInfo_1779" style="display: none;"><span style="float: right;">30 yd range</span><span style="float: left;">16% of base mana</span>
<br>
<span style="float: left;">1.5 sec cast</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1779_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1909_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_painandsuffering.jpg');">
<div class="talentHolder
						 disabled" id="1909_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1909);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1909_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col2" id="1907_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_mindtwisting.jpg');">
<div class="talentHolder
						 disabled" id="1907_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1907);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1907_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col1" id="1910_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_dispersion.jpg');">
<div class="talentHolder
						 disabled" id="1910_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1910);">
<span id="spellInfo_1910" style="display: none;"><span style="float: right;">2 min cooldown</span><span style="float: left;">Instant</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1910_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
</div>
<div class="talentTreeInfo" style="background: url(wow-icons/_images/21x21/spell_shadow_shadowwordpain.png) 0 0 no-repeat;">
<span id="treeName_2_sdfkte75" style="font-weight: bold;">Shadow</span> &nbsp;<span id="treeSpent_2_sdfkte75">0</span>
</div>
</div>
<table border="0" cellpadding="0" cellspacing="0" class="resetExportHolder">
<tr>
<td><a class="awesomeButton awesomeButton-exportBuild" href="#" id="linkToBuild_sdfkte75" target="_blank"><span>
<div class="staticTip" onmouseover="setTipText('Click to export a copy of this build into the talent calculator')">Export Build</div>
</span></a></td>
</tr>
</table>
</div>
</div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<script type="text/javascript">
				$(document).ready(function(){
					initCharTalents();			
				});
			</script>
</div>
</div>
</div>
</div>
<div class="data-shadow-bot">
<!---->
</div>
</div>