<xsl-template name="head-content">
<script src="_js/tools/talent-calc.js" type="text/javascript"></script>
</xsl-template>
<script type="text/javascript">
		var talentData_sdfkte75 = [
		
			{
				id:   "Arms",
				name: "Arms",
				talents: [
				
					{
						id:     124,
						tier:   0,
						column: 0,
						name:  "Improved Heroic Strike",
						icon:  "ability_rogue_ambush",
						
						ranks: [
						
							"Reduces the cost of your Heroic Strike ability by 1 rage point."
							,
							"Reduces the cost of your Heroic Strike ability by 2 rage points."
							,
							"Reduces the cost of your Heroic Strike ability by 3 rage points."
							
						]
					}
					,
					{
						id:     130,
						tier:   0,
						column: 1,
						name:  "Deflection",
						icon:  "ability_parry",
						
						ranks: [
						
							"Increases your Parry chance by 1%."
							,
							"Increases your Parry chance by 2%."
							,
							"Increases your Parry chance by 3%."
							,
							"Increases your Parry chance by 4%."
							,
							"Increases your Parry chance by 5%."
							
						]
					}
					,
					{
						id:     127,
						tier:   0,
						column: 2,
						name:  "Improved Rend",
						icon:  "ability_gouge",
						
						ranks: [
						
							"Increases the bleed damage done by your Rend ability by 10%."
							,
							"Increases the bleed damage done by your Rend ability by 20%."
							
						]
					}
					,
					{
						id:     126,
						tier:   1,
						column: 0,
						name:  "Improved Charge",
						icon:  "ability_warrior_charge",
						
						ranks: [
						
							"Increases the amount of rage generated by your Charge ability by 5."
							,
							"Increases the amount of rage generated by your Charge ability by 10."
							
						]
					}
					,
					{
						id:     641,
						tier:   1,
						column: 1,
						name:  "Iron Will",
						icon:  "spell_magic_magearmor",
						
						ranks: [
						
							"Reduces the duration of all Stun and Charm effects used against you by 7%."
							,
							"Reduces the duration of all Stun and Charm effects used against you by 14%."
							,
							"Reduces the duration of all Stun and Charm effects used against you by 20%."
							
						]
					}
					,
					{
						id:     128,
						tier:   1,
						column: 2,
						name:  "Tactical Mastery",
						icon:  "spell_nature_enchantarmor",
						
						ranks: [
						
							"You retain up to an additional 5 of your rage points when you change stances.  Also greatly increases the threat generated by your Bloodthirst and Mortal Strike abilities when you are in Defensive Stance."
							,
							"You retain up to an additional 10 of your rage points when you change stances.  Also greatly increases the threat generated by your Bloodthirst and Mortal Strike abilities when you are in Defensive Stance (More effective than Rank 1)."
							,
							"You retain up to an additional 15 of your rage points when you change stances.  Also greatly increases the threat generated by your Bloodthirst and Mortal Strike abilities when you are in Defensive Stance (More effective than Rank 2)."
							
						]
					}
					,
					{
						id:     131,
						tier:   2,
						column: 0,
						name:  "Improved Overpower",
						icon:  "inv_sword_05",
						
						ranks: [
						
							"Increases the critical strike chance of your Overpower ability by 25%."
							,
							"Increases the critical strike chance of your Overpower ability by 50%."
							
						]
					}
					,
					{
						id:     137,
						tier:   2,
						column: 1,
						name:  "Anger Management",
						icon:  "spell_holy_blessingofstamina",
						
						ranks: [
						
							"Generates 1 rage per 3 seconds."
							
						]
					}
					,
					{
						id:     662,
						tier:   2,
						column: 2,
						name:  "Impale",
						icon:  "ability_searingarrow",
						
						ranks: [
						
							"Increases the critical strike damage bonus of your abilities by 10%."
							,
							"Increases the critical strike damage bonus of your abilities by 20%."
							
						]
					}
					,
					{
						id:     121,
						tier:   2,
						column: 3,
						name:  "Deep Wounds",
						icon:  "ability_backstab",
						
							requires: 662,
						
						ranks: [
						
							"Your critical strikes cause the opponent to bleed, dealing 16% of your melee weapon's average damage over 6 sec."
							,
							"Your critical strikes cause the opponent to bleed, dealing 32% of your melee weapon's average damage over 6 sec."
							,
							"Your critical strikes cause the opponent to bleed, dealing 48% of your melee weapon's average damage over 6 sec."
							
						]
					}
					,
					{
						id:     136,
						tier:   3,
						column: 1,
						name:  "Two-Handed Weapon Specialization",
						icon:  "inv_axe_09",
						
						ranks: [
						
							"Increases the damage you deal with two-handed melee weapons by 2%."
							,
							"Increases the damage you deal with two-handed melee weapons by 4%."
							,
							"Increases the damage you deal with two-handed melee weapons by 6%."
							
						]
					}
					,
					{
						id:     2232,
						tier:   3,
						column: 2,
						name:  "Taste for Blood",
						icon:  "ability_rogue_hungerforblood",
						
						ranks: [
						
							"Whenever your Rend ability causes damage, you have a 33% chance of allowing the use of your Overpower ability for 9 sec.  1 charge.  This effect will not occur more than once every 6 sec."
							,
							"Whenever your Rend ability causes damage, you have a 66% chance of allowing the use of your Overpower ability for 9 sec.  1 charge.  This effect will not occur more than once every 6 sec."
							,
							"Whenever your Rend ability causes damage, you have a 100% chance of allowing the use of your Overpower ability for 9 sec.  1 charge.  This effect will not occur more than once every 6 sec."
							
						]
					}
					,
					{
						id:     132,
						tier:   4,
						column: 0,
						name:  "Poleaxe Specialization",
						icon:  "inv_axe_06",
						
						ranks: [
						
							"Increases your chance to get a critical strike and the critical damage caused with Axes and Polearms by 1%."
							,
							"Increases your chance to get a critical strike and the critical damage caused with Axes and Polearms by 2%."
							,
							"Increases your chance to get a critical strike and the critical damage caused with Axes and Polearms by 3%."
							,
							"Increases your chance to get a critical strike and the critical damage caused with Axes and Polearms by 4%."
							,
							"Increases your chance to get a critical strike and the critical damage caused with Axes and Polearms by 5%."
							
						]
					}
					,
					{
						id:     133,
						tier:   4,
						column: 1,
						name:  "Sweeping Strikes",
						icon:  "ability_rogue_slicedice",
						
						ranks: [
						
							"Your next 5 melee attacks strike an additional nearby opponent."
							
						]
					}
					,
					{
						id:     125,
						tier:   4,
						column: 2,
						name:  "Mace Specialization",
						icon:  "inv_mace_01",
						
						ranks: [
						
							"Your attacks with maces ignore up to 3% of your opponent's armor."
							,
							"Your attacks with maces ignore up to 6% of your opponent's armor."
							,
							"Your attacks with maces ignore up to 9% of your opponent's armor."
							,
							"Your attacks with maces ignore up to 12% of your opponent's armor."
							,
							"Your attacks with maces ignore up to 15% of your opponent's armor."
							
						]
					}
					,
					{
						id:     123,
						tier:   4,
						column: 3,
						name:  "Sword Specialization",
						icon:  "inv_sword_27",
						
						ranks: [
						
							"Gives you a 2% chance to get an extra attack on the same target after hitting your target with your Sword.  This effect cannot occur more than once every 6 seconds."
							,
							"Gives you a 4% chance to get an extra attack on the same target after hitting your target with your Sword.  This effect cannot occur more than once every 6 seconds."
							,
							"Gives you a 6% chance to get an extra attack on the same target after hitting your target with your Sword.  This effect cannot occur more than once every 6 seconds."
							,
							"Gives you a 8% chance to get an extra attack on the same target after hitting your target with your Sword.  This effect cannot occur more than once every 6 seconds."
							,
							"Gives you a 10% chance to get an extra attack on the same target after hitting your target with your Sword.  This effect cannot occur more than once every 6 seconds."
							
						]
					}
					,
					{
						id:     134,
						tier:   5,
						column: 0,
						name:  "Weapon Mastery",
						icon:  "ability_warrior_weaponmastery",
						
						ranks: [
						
							"Reduces the chance for your attacks to be dodged by 1% and reduces the duration of all Disarm effects used against you by 25%.  This does not stack with other Disarm duration reducing effects."
							,
							"Reduces the chance for your attacks to be dodged by 2% and reduces the duration of all Disarm effects used against you by 50%.  This does not stack with other Disarm duration reducing effects."
							
						]
					}
					,
					{
						id:     129,
						tier:   5,
						column: 2,
						name:  "Improved Hamstring",
						icon:  "ability_shockwave",
						
						ranks: [
						
							"Gives your Hamstring ability a 5% chance to immobilize the target for 5 sec."
							,
							"Gives your Hamstring ability a 10% chance to immobilize the target for 5 sec."
							,
							"Gives your Hamstring ability a 15% chance to immobilize the target for 5 sec."
							
						]
					}
					,
					{
						id:     1859,
						tier:   5,
						column: 3,
						name:  "Trauma",
						icon:  "ability_warrior_bloodnova",
						
						ranks: [
						
							"Your melee critical strikes increase the effectiveness of Bleed effects on the target by 15% for 15 sec."
							,
							"Your melee critical strikes increase the effectiveness of Bleed effects on the target by 30% for 15 sec."
							
						]
					}
					,
					{
						id:     1663,
						tier:   6,
						column: 0,
						name:  "Second Wind",
						icon:  "ability_hunter_harass",
						
						ranks: [
						
							"Whenever you are struck by a Stun or Immobilize effect you will generate 10 rage and 5% of your total health over 10 sec."
							,
							"Whenever you are struck by a Stun or Immobilize effect you will generate 20 rage and 10% of your total health over 10 sec."
							
						]
					}
					,
					{
						id:     135,
						tier:   6,
						column: 1,
						name:  "Mortal Strike",
						icon:  "ability_warrior_savageblow",
						
							requires: 133,
						
						ranks: [
						
							"A vicious strike that deals weapon damage plus 85 and wounds the target, reducing the effectiveness of any healing by 50% for 10 sec."
							
						]
					}
					,
					{
						id:     1862,
						tier:   6,
						column: 2,
						name:  "Strength of Arms",
						icon:  "ability_warrior_offensivestance",
						
						ranks: [
						
							"Increases your total Strength and Stamina by 2% and your Expertise by 2."
							,
							"Increases your total Strength and Stamina by 4% and your Expertise by 4."
							
						]
					}
					,
					{
						id:     2233,
						tier:   6,
						column: 3,
						name:  "Improved Slam",
						icon:  "ability_warrior_decisivestrike",
						
						ranks: [
						
							"Decreases the swing time of your Slam ability by 0.5 sec."
							,
							"Decreases the swing time of your Slam ability by 1 sec."
							
						]
					}
					,
					{
						id:     2283,
						tier:   7,
						column: 0,
						name:  "Juggernaut",
						icon:  "ability_warrior_bullrush",
						
						ranks: [
						
							"Your Charge ability is now usable while in combat, but the cooldown on Charge is increased by 5 sec. Following a Charge, your next Slam or Mortal Strike has an additional 25% chance to critically hit if used within 10 sec."
							
						]
					}
					,
					{
						id:     1824,
						tier:   7,
						column: 1,
						name:  "Improved Mortal Strike",
						icon:  "ability_warrior_savageblow",
						
							requires: 135,
						
						ranks: [
						
							"Increases the damage caused by your Mortal Strike ability by 3% and reduces the cooldown by 0.3 sec."
							,
							"Increases the damage caused by your Mortal Strike ability by 6% and reduces the cooldown by 0.7 sec."
							,
							"Increases the damage caused by your Mortal Strike ability by 10% and reduces the cooldown by 1 sec."
							
						]
					}
					,
					{
						id:     1860,
						tier:   7,
						column: 2,
						name:  "Unrelenting Assault",
						icon:  "ability_warrior_unrelentingassault",
						
						ranks: [
						
							"Reduces the cooldown of your Overpower and Revenge abilities by 2 secs and increases the damage done by both abilities by 10%.  In addition, if you strike a player with Overpower while they are casting, their magical damage and healing will be reduced by 25% for 6 sec."
							,
							"Reduces the cooldown of your Overpower and Revenge abilities by 4 secs and increases the damage done by both abilities by 20%.  In addition, if you strike a player with Overpower while they are casting, their magical damage and healing will be reduced by 50% for 6 sec."
							
						]
					}
					,
					{
						id:     1662,
						tier:   8,
						column: 0,
						name:  "Sudden Death",
						icon:  "ability_warrior_improveddisciplines",
						
						ranks: [
						
							"Your melee hits have a 3% chance of allowing the use of Execute regardless of the target's health state.  In addition, you keep at least 3 rage after using Execute."
							,
							"Your melee hits have a 6% chance of allowing the use of Execute regardless of the target's health state.  In addition, you keep at least 7 rage after using Execute."
							,
							"Your melee hits have a 9% chance of allowing the use of Execute regardless of the target's health state.  In addition, you keep at least 10 rage after using Execute."
							
						]
					}
					,
					{
						id:     1661,
						tier:   8,
						column: 1,
						name:  "Endless Rage",
						icon:  "ability_warrior_endlessrage",
						
						ranks: [
						
							"You generate 25% more rage from damage dealt."
							
						]
					}
					,
					{
						id:     1664,
						tier:   8,
						column: 2,
						name:  "Blood Frenzy",
						icon:  "ability_warrior_bloodfrenzy",
						
						ranks: [
						
							"Increases your melee attack speed by 5%.  In addition your Rend and Deep Wounds abilities also increase all physical damage caused to that target by 2%."
							,
							"Increases your melee attack speed by 10%.  In addition your Rend and Deep Wounds abilities also increase all physical damage caused to that target by 4%."
							
						]
					}
					,
					{
						id:     2231,
						tier:   9,
						column: 1,
						name:  "Wrecking Crew",
						icon:  "ability_warrior_trauma",
						
						ranks: [
						
							"Your melee critical hits Enrage you, increasing all damage caused by 2% for 12 sec.  This effect does not stack with Enrage."
							,
							"Your melee critical hits Enrage you, increasing all damage caused by 4% for 12 sec.  This effect does not stack with Enrage."
							,
							"Your melee critical hits Enrage you, increasing all damage caused by 6% for 12 sec.  This effect does not stack with Enrage."
							,
							"Your melee critical hits Enrage you, increasing all damage caused by 8% for 12 sec.  This effect does not stack with Enrage."
							,
							"Your melee critical hits Enrage you, increasing all damage caused by 10% for 12 sec.  This effect does not stack with Enrage."
							
						]
					}
					,
					{
						id:     1863,
						tier:   10,
						column: 1,
						name:  "Bladestorm",
						icon:  "ability_warrior_bladestorm",
						
						ranks: [
						
							"Instantly Whirlwind up to 4 nearby targets and for the next 6 sec you will perform a whirlwind attack every 1 sec.  While under the effects of Bladestorm, you can move but cannot perform any other abilities but you do not feel pity or remorse or fear and you cannot be stopped unless killed."
							
						]
					}
					
				]
			}
			,
			{
				id:   "Fury",
				name: "Fury",
				talents: [
				
					{
						id:     2250,
						tier:   0,
						column: 0,
						name:  "Armored to the Teeth",
						icon:  "inv_shoulder_22",
						
						ranks: [
						
							"Increases your attack power by 1 for every 108 armor value you have."
							,
							"Increases your attack power by 2 for every 108 armor value you have."
							,
							"Increases your attack power by 3 for every 108 armor value you have."
							
						]
					}
					,
					{
						id:     158,
						tier:   0,
						column: 1,
						name:  "Booming Voice",
						icon:  "spell_nature_purge",
						
						ranks: [
						
							"Increases the area of effect and duration of your Battle Shout, Demoralizing Shout and Commanding Shout by 25%."
							,
							"Increases the area of effect and duration of your Battle Shout, Demoralizing Shout and Commanding Shout by 50%."
							
						]
					}
					,
					{
						id:     157,
						tier:   0,
						column: 2,
						name:  "Cruelty",
						icon:  "ability_rogue_eviscerate",
						
						ranks: [
						
							"Increases your chance to get a critical strike with melee weapons by 1%."
							,
							"Increases your chance to get a critical strike with melee weapons by 2%."
							,
							"Increases your chance to get a critical strike with melee weapons by 3%."
							,
							"Increases your chance to get a critical strike with melee weapons by 4%."
							,
							"Increases your chance to get a critical strike with melee weapons by 5%."
							
						]
					}
					,
					{
						id:     161,
						tier:   1,
						column: 1,
						name:  "Improved Demoralizing Shout",
						icon:  "ability_warrior_warcry",
						
						ranks: [
						
							"Increases the melee attack power reduction of your Demoralizing Shout by 8%."
							,
							"Increases the melee attack power reduction of your Demoralizing Shout by 16%."
							,
							"Increases the melee attack power reduction of your Demoralizing Shout by 24%."
							,
							"Increases the melee attack power reduction of your Demoralizing Shout by 32%."
							,
							"Increases the melee attack power reduction of your Demoralizing Shout by 40%."
							
						]
					}
					,
					{
						id:     159,
						tier:   1,
						column: 2,
						name:  "Unbridled Wrath",
						icon:  "spell_nature_stoneclawtotem",
						
						ranks: [
						
							"Gives you a chance to generate an additional rage point when you deal melee damage with a weapon."
							,
							"Gives you a chance to generate an additional rage point when you deal melee damage with a weapon.  Effect occurs more often than Unbridled Wrath (Rank 1)."
							,
							"Gives you a chance to generate an additional rage point when you deal melee damage with a weapon.  Effect occurs more often than Unbridled Wrath (Rank 2)."
							,
							"Gives you a chance to generate an additional rage point when you deal melee damage with a weapon.  Effect occurs more often than Unbridled Wrath (Rank 3)."
							,
							"Gives you a chance to generate an additional rage point when you deal melee damage with a weapon.  Effect occurs more often than Unbridled Wrath (Rank 4)."
							
						]
					}
					,
					{
						id:     166,
						tier:   2,
						column: 0,
						name:  "Improved Cleave",
						icon:  "ability_warrior_cleave",
						
						ranks: [
						
							"Increases the bonus damage done by your Cleave ability by 40%."
							,
							"Increases the bonus damage done by your Cleave ability by 80%."
							,
							"Increases the bonus damage done by your Cleave ability by 120%."
							
						]
					}
					,
					{
						id:     160,
						tier:   2,
						column: 1,
						name:  "Piercing Howl",
						icon:  "spell_shadow_deathscream",
						
						ranks: [
						
							"Causes all enemies within 10 yards to be Dazed, reducing movement speed by 50% for 6 sec."
							
						]
					}
					,
					{
						id:     661,
						tier:   2,
						column: 2,
						name:  "Blood Craze",
						icon:  "spell_shadow_summonimp",
						
						ranks: [
						
							"Regenerates 2% of your total Health over 6 sec after being the victim of a critical strike."
							,
							"Regenerates 4% of your total Health over 6 sec after being the victim of a critical strike."
							,
							"Regenerates 6% of your total Health over 6 sec after being the victim of a critical strike."
							
						]
					}
					,
					{
						id:     154,
						tier:   2,
						column: 3,
						name:  "Commanding Presence",
						icon:  "spell_nature_focusedmind",
						
						ranks: [
						
							"Increases the melee attack power bonus of your Battle Shout and the health bonus of your Commanding Shout by 5%."
							,
							"Increases the melee attack power bonus of your Battle Shout and the health bonus of your Commanding Shout by 10%."
							,
							"Increases the melee attack power bonus of your Battle Shout and the health bonus of your Commanding Shout by 15%."
							,
							"Increases the melee attack power bonus of your Battle Shout and the health bonus of your Commanding Shout by 20%."
							,
							"Increases the melee attack power bonus of your Battle Shout and the health bonus of your Commanding Shout by 25%."
							
						]
					}
					,
					{
						id:     1581,
						tier:   3,
						column: 0,
						name:  "Dual Wield Specialization",
						icon:  "ability_dualwield",
						
						ranks: [
						
							"Increases the damage done by your offhand weapon by 5%."
							,
							"Increases the damage done by your offhand weapon by 10%."
							,
							"Increases the damage done by your offhand weapon by 15%."
							,
							"Increases the damage done by your offhand weapon by 20%."
							,
							"Increases the damage done by your offhand weapon by 25%."
							
						]
					}
					,
					{
						id:     1542,
						tier:   3,
						column: 1,
						name:  "Improved Execute",
						icon:  "inv_sword_48",
						
						ranks: [
						
							"Reduces the rage cost of your Execute ability by 2."
							,
							"Reduces the rage cost of your Execute ability by 5."
							
						]
					}
					,
					{
						id:     155,
						tier:   3,
						column: 2,
						name:  "Enrage",
						icon:  "spell_shadow_unholyfrenzy",
						
						ranks: [
						
							"Gives you a 30% chance to receive a 2% damage bonus for 12 sec after being the victim of a damaging attack.  This effect does not stack with Wrecking Crew."
							,
							"Gives you a 30% chance to receive a 4% damage bonus for 12 sec after being the victim of a damaging attack.  This effect does not stack with Wrecking Crew."
							,
							"Gives you a 30% chance to receive a 6% damage bonus for 12 sec after being the victim of a damaging attack.  This effect does not stack with Wrecking Crew."
							,
							"Gives you a 30% chance to receive a 8% damage bonus for 12 sec after being the victim of a damaging attack.  This effect does not stack with Wrecking Crew."
							,
							"Gives you a 30% chance to receive a 10% damage bonus for 12 sec after being the victim of a damaging attack.  This effect does not stack with Wrecking Crew."
							
						]
					}
					,
					{
						id:     1657,
						tier:   4,
						column: 0,
						name:  "Precision",
						icon:  "ability_marksmanship",
						
						ranks: [
						
							"Increases your chance to hit with melee weapons by 1%."
							,
							"Increases your chance to hit with melee weapons by 2%."
							,
							"Increases your chance to hit with melee weapons by 3%."
							
						]
					}
					,
					{
						id:     165,
						tier:   4,
						column: 1,
						name:  "Death Wish",
						icon:  "spell_shadow_deathpact",
						
						ranks: [
						
							"When activated you become enraged, increasing your physical damage by 20% but increasing all damage taken by 5%.  Lasts 30 sec."
							
						]
					}
					,
					{
						id:     1543,
						tier:   4,
						column: 2,
						name:  "Improved Intercept",
						icon:  "ability_rogue_sprint",
						
						ranks: [
						
							"Reduces the cooldown of your Intercept ability by 5 sec."
							,
							"Reduces the cooldown of your Intercept ability by 10 sec."
							
						]
					}
					,
					{
						id:     1541,
						tier:   5,
						column: 0,
						name:  "Improved Berserker Rage",
						icon:  "spell_nature_ancestralguardian",
						
						ranks: [
						
							"The Berserker Rage ability will generate 10 rage when used."
							,
							"The Berserker Rage ability will generate 20 rage when used."
							
						]
					}
					,
					{
						id:     156,
						tier:   5,
						column: 2,
						name:  "Flurry",
						icon:  "ability_ghoulfrenzy",
						
						ranks: [
						
							"Increases your attack speed by 5% for your next 3 swings after dealing a melee critical strike."
							,
							"Increases your attack speed by 10% for your next 3 swings after dealing a melee critical strike."
							,
							"Increases your attack speed by 15% for your next 3 swings after dealing a melee critical strike."
							,
							"Increases your attack speed by 20% for your next 3 swings after dealing a melee critical strike."
							,
							"Increases your attack speed by 25% for your next 3 swings after dealing a melee critical strike."
							
						]
					}
					,
					{
						id:     1864,
						tier:   6,
						column: 0,
						name:  "Intensify Rage",
						icon:  "ability_warrior_endlessrage",
						
						ranks: [
						
							"Reduces the cooldown of your Bloodrage, Berserker Rage, Recklessness and Death Wish abilities by 11%."
							,
							"Reduces the cooldown of your Bloodrage, Berserker Rage, Recklessness and Death Wish abilities by 22%."
							,
							"Reduces the cooldown of your Bloodrage, Berserker Rage, Recklessness and Death Wish abilities by 33%."
							
						]
					}
					,
					{
						id:     167,
						tier:   6,
						column: 1,
						name:  "Bloodthirst",
						icon:  "spell_nature_bloodlust",
						
							requires: 165,
						
						ranks: [
						
							"Instantly attack the target causing 13 damage.  In addition, the next 3 successful melee attacks will restore 1% of max health.  This effect lasts 8 sec.  Damage is based on your attack power."
							
						]
					}
					,
					{
						id:     1655,
						tier:   6,
						column: 3,
						name:  "Improved Whirlwind",
						icon:  "ability_whirlwind",
						
						ranks: [
						
							"Increases the damage of your Whirlwind ability by 10%."
							,
							"Increases the damage of your Whirlwind ability by 20%."
							
						]
					}
					,
					{
						id:     1865,
						tier:   7,
						column: 0,
						name:  "Furious Attacks",
						icon:  "ability_warrior_furiousresolve",
						
						ranks: [
						
							"Your normal melee attacks have a chance to reduce all healing done to the target by 25% for 10 sec.  This can stack up to 2 times."
							,
							"Your normal melee attacks have a chance to reduce all healing done to the target by 25% for 10 sec.  This can stack up to 2 times.  This occurs more often than Furious Attacks (Rank 1)."
							
						]
					}
					,
					{
						id:     1658,
						tier:   7,
						column: 3,
						name:  "Improved Berserker Stance",
						icon:  "ability_racial_avatar",
						
						ranks: [
						
							"Increases Strength by 4% and reduces threat caused by 2% while in Berserker Stance."
							,
							"Increases Strength by 8% and reduces threat caused by 4% while in Berserker Stance."
							,
							"Increases Strength by 12% and reduces threat caused by 6% while in Berserker Stance."
							,
							"Increases Strength by 16% and reduces threat caused by 8% while in Berserker Stance."
							,
							"Increases Strength by 20% and reduces threat caused by 10% while in Berserker Stance."
							
						]
					}
					,
					{
						id:     1868,
						tier:   8,
						column: 0,
						name:  "Heroic Fury",
						icon:  "ability_heroicleap",
						
						ranks: [
						
							"Removes any Immobilization effects and refreshes the cooldown of your Intercept ability."
							
						]
					}
					,
					{
						id:     1659,
						tier:   8,
						column: 1,
						name:  "Rampage",
						icon:  "ability_warrior_rampage",
						
							requires: 167,
						
						ranks: [
						
							"Your melee critical hits cause you to go on a rampage, increasing ranged and melee critical hit chance of all party and raid members within 45 yds by 5%.  Lasts 10 sec."
							
						]
					}
					,
					{
						id:     1866,
						tier:   8,
						column: 2,
						name:  "Bloodsurge",
						icon:  "ability_warrior_bloodsurge",
						
							requires: 167,
						
						ranks: [
						
							"Your Heroic Strike, Bloodthirst, and Whirlwind hits have a 7% chance of making your next Slam instant for 5 sec."
							,
							"Your Heroic Strike, Bloodthirst, and Whirlwind hits have a 13% chance of making your next Slam instant for 5 sec."
							,
							"Your Heroic Strike, Bloodthirst, and Whirlwind hits have a 20% chance of making your next Slam instant for 5 sec."
							
						]
					}
					,
					{
						id:     2234,
						tier:   9,
						column: 1,
						name:  "Unending Fury",
						icon:  "ability_warrior_intensifyrage",
						
						ranks: [
						
							"Increases the damage done by your Slam, Whirlwind and Bloodthirst abilities by 2%."
							,
							"Increases the damage done by your Slam, Whirlwind and Bloodthirst abilities by 4%."
							,
							"Increases the damage done by your Slam, Whirlwind and Bloodthirst abilities by 6%."
							,
							"Increases the damage done by your Slam, Whirlwind and Bloodthirst abilities by 8%."
							,
							"Increases the damage done by your Slam, Whirlwind and Bloodthirst abilities by 10%."
							
						]
					}
					,
					{
						id:     1867,
						tier:   10,
						column: 1,
						name:  "Titan's Grip",
						icon:  "ability_warrior_titansgrip",
						
						ranks: [
						
							"Allows you to equip two-handed axes, maces and swords in one hand.  While you have a two-handed weapon equipped in one hand, your physical damage done is reduced by 10%."
							
						]
					}
					
				]
			}
			,
			{
				id:   "Protection",
				name: "Protection",
				talents: [
				
					{
						id:     142,
						tier:   0,
						column: 0,
						name:  "Improved Bloodrage",
						icon:  "ability_racial_bloodrage",
						
						ranks: [
						
							"Increases the rage generated by your Bloodrage ability by 25%."
							,
							"Increases the rage generated by your Bloodrage ability by 50%."
							
						]
					}
					,
					{
						id:     1601,
						tier:   0,
						column: 1,
						name:  "Shield Specialization",
						icon:  "inv_shield_06",
						
						ranks: [
						
							"Increases your chance to block attacks with a shield by 1% and has a 20% chance to generate 5 rage when a block, dodge, or parry occurs."
							,
							"Increases your chance to block attacks with a shield by 2% and has a 40% chance to generate 5 rage when a block, dodge, or parry occurs."
							,
							"Increases your chance to block attacks with a shield by 3% and has a 60% chance to generate 5 rage when a block, dodge, or parry occurs."
							,
							"Increases your chance to block attacks with a shield by 4% and has a 80% chance to generate 5 rage when a block, dodge, or parry occurs."
							,
							"Increases your chance to block attacks with a shield by 5% and has a 100% chance to generate 5 rage when a block, dodge, or parry occurs."
							
						]
					}
					,
					{
						id:     141,
						tier:   0,
						column: 2,
						name:  "Improved Thunder Clap",
						icon:  "ability_thunderclap",
						
						ranks: [
						
							"Reduces the cost of your Thunder Clap ability by 1 rage point and increases the damage by 10% and the slowing effect by an additional 4%."
							,
							"Reduces the cost of your Thunder Clap ability by 2 rage points and increases the damage by 20% and the slowing effect by an additional 7%."
							,
							"Reduces the cost of your Thunder Clap ability by 4 rage points and increases the damage by 30% and the slowing effect by an additional 10%."
							
						]
					}
					,
					{
						id:     144,
						tier:   1,
						column: 1,
						name:  "Incite",
						icon:  "ability_warrior_incite",
						
						ranks: [
						
							"Increases the critical strike chance of your Heroic Strike, Thunder Clap and Cleave abilities by 5%."
							,
							"Increases the critical strike chance of your Heroic Strike, Thunder Clap and Cleave abilities by 10%."
							,
							"Increases the critical strike chance of your Heroic Strike, Thunder Clap and Cleave abilities by 15%."
							
						]
					}
					,
					{
						id:     138,
						tier:   1,
						column: 2,
						name:  "Anticipation",
						icon:  "spell_nature_mirrorimage",
						
						ranks: [
						
							"Increases your Dodge chance by 1%."
							,
							"Increases your Dodge chance by 2%."
							,
							"Increases your Dodge chance by 3%."
							,
							"Increases your Dodge chance by 4%."
							,
							"Increases your Dodge chance by 5%."
							
						]
					}
					,
					{
						id:     153,
						tier:   2,
						column: 0,
						name:  "Last Stand",
						icon:  "spell_holy_ashestoashes",
						
						ranks: [
						
							"When activated, this ability temporarily grants you 30% of your maximum health for 20 sec.  After the effect expires, the health is lost."
							
						]
					}
					,
					{
						id:     147,
						tier:   2,
						column: 1,
						name:  "Improved Revenge",
						icon:  "ability_warrior_revenge",
						
						ranks: [
						
							"Increases damage of your Revenge ability by 10% and gives a 25% chance to stun the target for 3 sec."
							,
							"Increases damage of your Revenge ability by 20% and gives a 50% chance to stun the target for 3 sec."
							
						]
					}
					,
					{
						id:     1654,
						tier:   2,
						column: 2,
						name:  "Shield Mastery",
						icon:  "ability_warrior_shieldmastery",
						
						ranks: [
						
							"Increases your block value by 15% and reduces the cooldown of your Shield Block ability by 10 sec."
							,
							"Increases your block value by 30% and reduces the cooldown of your Shield Block ability by 20 sec."
							
						]
					}
					,
					{
						id:     140,
						tier:   2,
						column: 3,
						name:  "Toughness",
						icon:  "spell_holy_devotion",
						
						ranks: [
						
							"Increases your armor value from items by 2% and reduces the duration of all movement slowing effects by 6%."
							,
							"Increases your armor value from items by 4% and reduces the duration of all movement slowing effects by 12%."
							,
							"Increases your armor value from items by 6% and reduces the duration of all movement slowing effects by 18%."
							,
							"Increases your armor value from items by 8% and reduces the duration of all movement slowing effects by 24%."
							,
							"Increases your armor value from items by 10% and reduces the duration of all movement slowing effects by 30%."
							
						]
					}
					,
					{
						id:     2247,
						tier:   3,
						column: 0,
						name:  "Improved Spell Reflection",
						icon:  "ability_warrior_shieldreflection",
						
						ranks: [
						
							"Reduces the chance you'll be hit by spells by 2% and when the ability is used it will reflect the first spell cast against the 2 closest party members within 20 yards."
							,
							"Reduces the chance you'll be hit by spells by 4% and when the ability is used it will reflect the first spell cast against the 4 closest party members within 20 yards."
							
						]
					}
					,
					{
						id:     151,
						tier:   3,
						column: 1,
						name:  "Improved Disarm",
						icon:  "ability_warrior_disarm",
						
						ranks: [
						
							"Reduces the cooldown of your Disarm ability by 10 sec and causes the target to take an additional 5% damage while disarmed."
							,
							"Reduces the cooldown of your Disarm ability by 20 sec and causes the target to take an additional 10% damage while disarmed."
							
						]
					}
					,
					{
						id:     146,
						tier:   3,
						column: 2,
						name:  "Puncture",
						icon:  "ability_warrior_sunder",
						
						ranks: [
						
							"Reduces the rage cost of your Sunder Armor and Devastate abilities by 1."
							,
							"Reduces the rage cost of your Sunder Armor and Devastate abilities by 2."
							,
							"Reduces the rage cost of your Sunder Armor and Devastate abilities by 3."
							
						]
					}
					,
					{
						id:     150,
						tier:   4,
						column: 0,
						name:  "Improved Disciplines",
						icon:  "ability_warrior_shieldwall",
						
						ranks: [
						
							"Reduces the cooldown of your Shield Wall, Retaliation and Recklessness abilities by 30 secs."
							,
							"Reduces the cooldown of your Shield Wall, Retaliation and Recklessness abilities by 60 secs."
							
						]
					}
					,
					{
						id:     152,
						tier:   4,
						column: 1,
						name:  "Concussion Blow",
						icon:  "ability_thunderbolt",
						
						ranks: [
						
							"Stuns the opponent for 5 sec and deals 20 damage (based on attack power)."
							
						]
					}
					,
					{
						id:     149,
						tier:   4,
						column: 2,
						name:  "Gag Order",
						icon:  "ability_warrior_shieldbash",
						
						ranks: [
						
							"Gives your Shield Bash and Heroic Throw abilities a 50% chance to silence the target for 3 sec and increases the damage of your Shield Slam ability by 5%."
							,
							"Gives your Shield Bash and Heroic Throw abilities a 100% chance to silence the target for 3 sec and increases the damage of your Shield Slam ability by 10%."
							
						]
					}
					,
					{
						id:     702,
						tier:   5,
						column: 2,
						name:  "One-Handed Weapon Specialization",
						icon:  "inv_sword_20",
						
						ranks: [
						
							"Increases physical damage you deal when a one-handed melee weapon is equipped by 2%."
							,
							"Increases physical damage you deal when a one-handed melee weapon is equipped by 4%."
							,
							"Increases physical damage you deal when a one-handed melee weapon is equipped by 6%."
							,
							"Increases physical damage you deal when a one-handed melee weapon is equipped by 8%."
							,
							"Increases physical damage you deal when a one-handed melee weapon is equipped by 10%."
							
						]
					}
					,
					{
						id:     1652,
						tier:   6,
						column: 0,
						name:  "Improved Defensive Stance",
						icon:  "ability_warrior_defensivestance",
						
						ranks: [
						
							"While in Defensive Stance all spell damage is reduced by 3% and when you Block, Parry or Dodge an attack you have a 50% chance to become Enraged, increasing Physical damage caused by 5% for 12 sec."
							,
							"While in Defensive Stance all spell damage is reduced by 6% and when you Block, Parry or Dodge an attack you have a 100% chance to become Enraged, increasing Physical damage caused by 10% for 12 sec."
							
						]
					}
					,
					{
						id:     148,
						tier:   6,
						column: 1,
						name:  "Vigilance",
						icon:  "ability_warrior_vigilance",
						
							requires: 152,
						
						ranks: [
						
							"Focus your protective gaze on a group or raid target, reducing their damage taken by 3% and transfers -10% of the threat they cause to you.  In addition, each time they are hit by an attack your Taunt cooldown is refreshed.  Lasts 30 min.  This effect can only be on one target at a time."
							
						]
					}
					,
					{
						id:     1660,
						tier:   6,
						column: 2,
						name:  "Focused Rage",
						icon:  "ability_warrior_focusedrage",
						
						ranks: [
						
							"Reduces the rage cost of your offensive abilities by 1."
							,
							"Reduces the rage cost of your offensive abilities by 2."
							,
							"Reduces the rage cost of your offensive abilities by 3."
							
						]
					}
					,
					{
						id:     1653,
						tier:   7,
						column: 1,
						name:  "Vitality",
						icon:  "inv_helmet_21",
						
						ranks: [
						
							"Increases your total Strength and Stamina by 2% and your Expertise by 2."
							,
							"Increases your total Strength and Stamina by 4% and your Expertise by 4."
							,
							"Increases your total Strength and Stamina by 6% and your Expertise by 6."
							
						]
					}
					,
					{
						id:     1870,
						tier:   7,
						column: 2,
						name:  "Safeguard",
						icon:  "ability_warrior_safeguard",
						
						ranks: [
						
							"Reduces damage taken by the target of your Intervene ability by 15% for 6 sec."
							,
							"Reduces damage taken by the target of your Intervene ability by 30% for 6 sec."
							
						]
					}
					,
					{
						id:     2236,
						tier:   8,
						column: 0,
						name:  "Warbringer",
						icon:  "ability_warrior_warbringer",
						
						ranks: [
						
							"Your Charge, Intercept and Intervene abilities are now usable while in combat and in any stance.  In addition, your Charge, Intercept and Intervene abilities will remove all movement impairing effects."
							
						]
					}
					,
					{
						id:     1666,
						tier:   8,
						column: 1,
						name:  "Devastate",
						icon:  "inv_sword_11",
						
						ranks: [
						
							"Sunder the target's armor causing the Sunder Armor effect.  In addition, causes 100% of weapon damage plus 48 for each application of Sunder Armor on the target.  The Sunder Armor effect can stack up to 5 times."
							
						]
					}
					,
					{
						id:     1893,
						tier:   8,
						column: 2,
						name:  "Critical Block",
						icon:  "ability_warrior_criticalblock",
						
						ranks: [
						
							"Your successful blocks have a 20% chance to block double the normal amount and increases your chance to critically hit with your Shield Slam ability by an additional 5%."
							,
							"Your successful blocks have a 40% chance to block double the normal amount and increases your chance to critically hit with your Shield Slam ability by an additional 10%."
							,
							"Your successful blocks have a 60% chance to block double the normal amount and increases your chance to critically hit with your Shield Slam ability by an additional 15%."
							
						]
					}
					,
					{
						id:     1871,
						tier:   9,
						column: 1,
						name:  "Sword and Board",
						icon:  "ability_warrior_swordandboard",
						
							requires: 1666,
						
						ranks: [
						
							"Increases the critical strike chance of your Devastate ability by 5% and when your Devastate or Revenge ability deals damage it has a 10% chance of refreshing the cooldown of your Shield Slam ability and reducing its cost by 100% for 5 sec."
							,
							"Increases the critical strike chance of your Devastate ability by 10% and when your Devastate or Revenge ability deals damage it has a 20% chance of refreshing the cooldown of your Shield Slam ability and reducing its cost by 100% for 5 sec."
							,
							"Increases the critical strike chance of your Devastate ability by 15% and when your Devastate or Revenge ability deals damage it has a 30% chance of refreshing the cooldown of your Shield Slam ability and reducing its cost by 100% for 5 sec."
							
						]
					}
					,
					{
						id:     2246,
						tier:   9,
						column: 2,
						name:  "Damage Shield",
						icon:  "inv_shield_31",
						
						ranks: [
						
							"Whenever you take damage from or block a melee attack you cause damage equal to 10% of your block value."
							,
							"Whenever you take damage from or block a melee attack you cause damage equal to 20% of your block value."
							
						]
					}
					,
					{
						id:     1872,
						tier:   10,
						column: 1,
						name:  "Shockwave",
						icon:  "ability_warrior_shockwave",
						
						ranks: [
						
							"Sends a wave of force in front of the warrior, causing 20 damage (based on attack power) and stunning all enemy targets within 10 yards in a frontal cone for 4 sec."
							
						]
					}
					
				]
			}
			
		];

		var petData_sdfkte75 = null;
		
	
		var textTalentStrSingle = "Requires {0} point in {1}.";
		var textTalentStrPlural = "Requires {0} points in {1}.";
		var textTalentRank = "Rank {0}/{1}";
		var textTalentNextRank = "Next Rank";
		var textTalentReqTreeTalents = "Requires {0} points in {1} Talents.";
		var textPrintableClassTalents = "{0} Talents";
		var textPrintableMinReqLevel = "Minimum Required Level: {0}";
		var textPrintableReqTalentPts = "Required Talent Points: {0}";
		var textPrintableTreeTalents = "{0} Talents";
		var textPrintablePtsPerTree = "{0} point(s)";
		var textPrintableDontWastePaper = "Don't waste paper!";

		var talentCalc = new TalentCalculator();

		$(document).ready(function() {

			talentCalc.initTalentCalc(
				"1", 
				"{{$talents}}", 
				"charPage",
				"false",
				"sdfkte75",
				talentData_sdfkte75,
				petData_sdfkte75
			);
		});
	</script>
<div class="talContainer" id="talContainer_sdfkte75">
<div class="talentFrame">
<div class="talentTree" id="Arms_tree_sdfkte75" style="margin-right: 3px; background-image: url('images/talents/bg/small/WarriorArms.jpg')">
<div class="tier">
<div class="talent staticTip col0" id="124_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/ability_rogue_ambush.jpg');">
<div class="talentHolder
						" id="124_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(124);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="124_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="130_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/ability_parry.jpg');">
<div class="talentHolder
						" id="130_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(130);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="130_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="127_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/ability_gouge.jpg');">
<div class="talentHolder
						" id="127_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(127);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="127_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="126_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_charge.jpg');">
<div class="talentHolder
						 disabled" id="126_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(126);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="126_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="641_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_magic_magearmor.jpg');">
<div class="talentHolder
						 disabled" id="641_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(641);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="641_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="128_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_nature_enchantarmor.jpg');">
<div class="talentHolder
						 disabled" id="128_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(128);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="128_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="131_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/inv_sword_05.jpg');">
<div class="talentHolder
						 disabled" id="131_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(131);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="131_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="137_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_blessingofstamina.jpg');">
<div class="talentHolder
						 disabled" id="137_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(137);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="137_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="662_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_searingarrow.jpg');">
<div class="talentHolder
						 disabled" id="662_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(662);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="662_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col3" id="121_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_backstab.jpg');">
<div class="talentHolder
						 disabled" id="121_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(121);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="121_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col1" id="136_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/inv_axe_09.jpg');">
<div class="talentHolder
						 disabled" id="136_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(136);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="136_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="2232_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_rogue_hungerforblood.jpg');">
<div class="talentHolder
						 disabled" id="2232_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(2232);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="2232_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="132_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/inv_axe_06.jpg');">
<div class="talentHolder
						 disabled" id="132_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(132);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="132_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="133_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_rogue_slicedice.jpg');">
<div class="talentHolder
						 disabled" id="133_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(133);">
<span id="spellInfo_133" style="display: none;"><span style="float: left;">30 Rage</span>
<br>
<span style="float: right;">30 sec cooldown</span><span style="float: left;">Instant</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="133_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="125_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/inv_mace_01.jpg');">
<div class="talentHolder
						 disabled" id="125_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(125);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="125_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
<div class="talent staticTip col3" id="123_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/inv_sword_27.jpg');">
<div class="talentHolder
						 disabled" id="123_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(123);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="123_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="134_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_weaponmastery.jpg');">
<div class="talentHolder
						 disabled" id="134_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(134);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="134_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="129_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_shockwave.jpg');">
<div class="talentHolder
						 disabled" id="129_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(129);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="129_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col3" id="1859_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_bloodnova.jpg');">
<div class="talentHolder
						 disabled" id="1859_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1859);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1859_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="1663_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_hunter_harass.jpg');">
<div class="talentHolder
						 disabled" id="1663_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1663);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1663_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="135_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_savageblow.jpg');">
<div class="talentHolder
						 disabled" id="135_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(135);">
<span id="spellInfo_135" style="display: none;"><span style="float: right;">Melee range</span><span style="float: left;">30 Rage</span>
<br>
<span style="float: right;">6 sec cooldown</span><span style="float: left;">Instant</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="135_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1862_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_offensivestance.jpg');">
<div class="talentHolder
						 disabled" id="1862_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1862);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1862_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col3" id="2233_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_decisivestrike.jpg');">
<div class="talentHolder
						 disabled" id="2233_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(2233);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="2233_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="2283_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_bullrush.jpg');">
<div class="talentHolder
						 disabled" id="2283_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(2283);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="2283_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="1824_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_savageblow.jpg');">
<div class="talentHolder
						 disabled" id="1824_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1824);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1824_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1860_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_unrelentingassault.jpg');">
<div class="talentHolder
						 disabled" id="1860_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1860);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1860_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="1662_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_improveddisciplines.jpg');">
<div class="talentHolder
						 disabled" id="1662_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1662);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1662_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="1661_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_endlessrage.jpg');">
<div class="talentHolder
						 disabled" id="1661_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1661);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1661_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1664_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_bloodfrenzy.jpg');">
<div class="talentHolder
						 disabled" id="1664_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1664);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1664_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col1" id="2231_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_trauma.jpg');">
<div class="talentHolder
						 disabled" id="2231_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(2231);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="2231_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col1" id="1863_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_bladestorm.jpg');">
<div class="talentHolder
						 disabled" id="1863_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1863);">
<span id="spellInfo_1863" style="display: none;"><span style="float: left;">25 Rage</span>
<br>
<span style="float: right;">1.5 min cooldown</span><span style="float: left;">Instant</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1863_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
</div>
<div class="talentTreeInfo" style="background: url(wow-icons/_images/21x21/ability_rogue_eviscerate.png) 0 0 no-repeat;">
<span id="treeName_0_sdfkte75" style="font-weight: bold;">Arms</span> &nbsp;<span id="treeSpent_0_sdfkte75">0</span>
</div>
</div>
<div class="talentTree" id="Fury_tree_sdfkte75" style="margin-right: 3px; background-image: url('images/talents/bg/small/WarriorFury.jpg')">
<div class="tier">
<div class="talent staticTip col0" id="2250_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/inv_shoulder_22.jpg');">
<div class="talentHolder
						" id="2250_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(2250);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="2250_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="158_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/spell_nature_purge.jpg');">
<div class="talentHolder
						" id="158_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(158);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="158_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="157_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/ability_rogue_eviscerate.jpg');">
<div class="talentHolder
						" id="157_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(157);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="157_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col1" id="161_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_warcry.jpg');">
<div class="talentHolder
						 disabled" id="161_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(161);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="161_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="159_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_nature_stoneclawtotem.jpg');">
<div class="talentHolder
						 disabled" id="159_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(159);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="159_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="166_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_cleave.jpg');">
<div class="talentHolder
						 disabled" id="166_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(166);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="166_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="160_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_deathscream.jpg');">
<div class="talentHolder
						 disabled" id="160_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(160);">
<span id="spellInfo_160" style="display: none;"><span style="float: left;">10 Rage</span>
<br>
<span style="float: left;">Instant</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="160_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="661_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_summonimp.jpg');">
<div class="talentHolder
						 disabled" id="661_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(661);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="661_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col3" id="154_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_nature_focusedmind.jpg');">
<div class="talentHolder
						 disabled" id="154_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(154);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="154_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="1581_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_dualwield.jpg');">
<div class="talentHolder
						 disabled" id="1581_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1581);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1581_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="1542_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/inv_sword_48.jpg');">
<div class="talentHolder
						 disabled" id="1542_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1542);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1542_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="155_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_unholyfrenzy.jpg');">
<div class="talentHolder
						 disabled" id="155_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(155);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="155_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="1657_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_marksmanship.jpg');">
<div class="talentHolder
						 disabled" id="1657_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1657);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1657_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="165_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_shadow_deathpact.jpg');">
<div class="talentHolder
						 disabled" id="165_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(165);">
<span id="spellInfo_165" style="display: none;"><span style="float: left;">10 Rage</span>
<br>
<span style="float: right;">3 min cooldown</span><span style="float: left;">Instant</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="165_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1543_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_rogue_sprint.jpg');">
<div class="talentHolder
						 disabled" id="1543_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1543);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1543_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="1541_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_nature_ancestralguardian.jpg');">
<div class="talentHolder
						 disabled" id="1541_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1541);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1541_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="156_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_ghoulfrenzy.jpg');">
<div class="talentHolder
						 disabled" id="156_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(156);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="156_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="1864_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_endlessrage.jpg');">
<div class="talentHolder
						 disabled" id="1864_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1864);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1864_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="167_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_nature_bloodlust.jpg');">
<div class="talentHolder
						 disabled" id="167_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(167);">
<span id="spellInfo_167" style="display: none;"><span style="float: right;">Melee range</span><span style="float: left;">20 Rage</span>
<br>
<span style="float: right;">4 sec cooldown</span><span style="float: left;">Instant</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="167_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col3" id="1655_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_whirlwind.jpg');">
<div class="talentHolder
						 disabled" id="1655_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1655);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1655_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="1865_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_furiousresolve.jpg');">
<div class="talentHolder
						 disabled" id="1865_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1865);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1865_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col3" id="1658_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_racial_avatar.jpg');">
<div class="talentHolder
						 disabled" id="1658_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1658);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1658_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="1868_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_heroicleap.jpg');">
<div class="talentHolder
						 disabled" id="1868_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1868);">
<span id="spellInfo_1868" style="display: none;"><span style="float: right;">45 sec cooldown</span><span style="float: left;">Instant</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1868_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="1659_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_rampage.jpg');">
<div class="talentHolder
						 disabled" id="1659_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1659);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1659_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1866_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_bloodsurge.jpg');">
<div class="talentHolder
						 disabled" id="1866_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1866);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1866_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col1" id="2234_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_intensifyrage.jpg');">
<div class="talentHolder
						 disabled" id="2234_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(2234);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="2234_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col1" id="1867_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_titansgrip.jpg');">
<div class="talentHolder
						 disabled" id="1867_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1867);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1867_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
</div>
<div class="talentTreeInfo" style="background: url(wow-icons/_images/21x21/ability_warrior_innerrage.png) 0 0 no-repeat;">
<span id="treeName_1_sdfkte75" style="font-weight: bold;">Fury</span> &nbsp;<span id="treeSpent_1_sdfkte75">0</span>
</div>
</div>
<div class="talentTree" id="Protection_tree_sdfkte75" style="background-image: url('images/talents/bg/small/WarriorProtection.jpg');">
<div class="tier">
<div class="talent staticTip col0" id="142_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/ability_racial_bloodrage.jpg');">
<div class="talentHolder
						" id="142_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(142);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="142_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="1601_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/inv_shield_06.jpg');">
<div class="talentHolder
						" id="1601_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1601);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1601_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="141_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/ability_thunderclap.jpg');">
<div class="talentHolder
						" id="141_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(141);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="141_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col1" id="144_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_incite.jpg');">
<div class="talentHolder
						 disabled" id="144_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(144);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="144_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="138_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_nature_mirrorimage.jpg');">
<div class="talentHolder
						 disabled" id="138_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(138);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="138_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="153_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_ashestoashes.jpg');">
<div class="talentHolder
						 disabled" id="153_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(153);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="153_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="147_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_revenge.jpg');">
<div class="talentHolder
						 disabled" id="147_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(147);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="147_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1654_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_shieldmastery.jpg');">
<div class="talentHolder
						 disabled" id="1654_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1654);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1654_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col3" id="140_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/spell_holy_devotion.jpg');">
<div class="talentHolder
						 disabled" id="140_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(140);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="140_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="2247_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_shieldreflection.jpg');">
<div class="talentHolder
						 disabled" id="2247_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(2247);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="2247_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="151_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_disarm.jpg');">
<div class="talentHolder
						 disabled" id="151_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(151);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="151_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="146_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_sunder.jpg');">
<div class="talentHolder
						 disabled" id="146_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(146);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="146_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="150_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_shieldwall.jpg');">
<div class="talentHolder
						 disabled" id="150_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(150);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="150_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="152_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_thunderbolt.jpg');">
<div class="talentHolder
						 disabled" id="152_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(152);">
<span id="spellInfo_152" style="display: none;"><span style="float: right;">Melee range</span><span style="float: left;">15 Rage</span>
<br>
<span style="float: right;">30 sec cooldown</span><span style="float: left;">Instant</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="152_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="149_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_shieldbash.jpg');">
<div class="talentHolder
						 disabled" id="149_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(149);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="149_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col2" id="702_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/inv_sword_20.jpg');">
<div class="talentHolder
						 disabled" id="702_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(702);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="702_numPoints_sdfkte75">0</span><span>/</span><span>5</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="1652_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_defensivestance.jpg');">
<div class="talentHolder
						 disabled" id="1652_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1652);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1652_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="148_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_vigilance.jpg');">
<div class="talentHolder
						 disabled" id="148_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(148);">
<span id="spellInfo_148" style="display: none;"><span style="float: left;">30 yd range</span>
<br>
<span style="float: left;">Instant</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="148_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1660_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_focusedrage.jpg');">
<div class="talentHolder
						 disabled" id="1660_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1660);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1660_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col1" id="1653_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/inv_helmet_21.jpg');">
<div class="talentHolder
						 disabled" id="1653_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1653);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1653_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1870_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_safeguard.jpg');">
<div class="talentHolder
						 disabled" id="1870_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1870);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1870_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col0" id="2236_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_warbringer.jpg');">
<div class="talentHolder
						 disabled" id="2236_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(2236);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="2236_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col1" id="1666_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/inv_sword_11.jpg');">
<div class="talentHolder
						 disabled" id="1666_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1666);">
<span id="spellInfo_1666" style="display: none;"><span style="float: right;">Melee range</span><span style="float: left;">15 Rage</span>
<br>
<span style="float: left;">Instant</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1666_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="1893_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_criticalblock.jpg');">
<div class="talentHolder
						 disabled" id="1893_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1893);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1893_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col1" id="1871_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_swordandboard.jpg');">
<div class="talentHolder
						 disabled" id="1871_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1871);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1871_numPoints_sdfkte75">0</span><span>/</span><span>3</span>
</div>
</div>
</div>
<div class="talent staticTip col2" id="2246_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/inv_shield_31.jpg');">
<div class="talentHolder
						 disabled" id="2246_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(2246);">
<div class="talentHover"></div>
<div class="rankCtr">
<span id="2246_numPoints_sdfkte75">0</span><span>/</span><span>2</span>
</div>
</div>
</div>
</div>
<div class="tier">
<div class="talent staticTip col1" id="1872_iconHolder_sdfkte75" style="background-image:url('wow-icons/_images/_talents31x31/grey/ability_warrior_shockwave.jpg');">
<div class="talentHolder
						 disabled" id="1872_talentHolder_sdfkte75" onclick="return false" onmouseover="talentCalc.makeTalentTooltip(1872);">
<span id="spellInfo_1872" style="display: none;"><span style="float: left;">15 Rage</span>
<br>
<span style="float: right;">20 sec cooldown</span><span style="float: left;">Instant</span></span>
<div class="talentHover"></div>
<div class="rankCtr">
<span id="1872_numPoints_sdfkte75">0</span><span>/</span><span>1</span>
</div>
</div>
</div>
</div>
<div class="talentTreeInfo" style="background: url(wow-icons/_images/21x21/inv_shield_06.png) 0 0 no-repeat;">
<span id="treeName_2_sdfkte75" style="font-weight: bold;">Protection</span> &nbsp;<span id="treeSpent_2_sdfkte75">0</span>
</div>
</div>
<table border="0" cellpadding="0" cellspacing="0" class="resetExportHolder">
<tr>
<td><a class="awesomeButton awesomeButton-exportBuild" href="#" id="linkToBuild_sdfkte75" target="_blank"><span>
<div class="staticTip" onmouseover="setTipText('Click to export a copy of this build into the talent calculator')">Export Build</div>
</span></a></td>
</tr>
</table>
</div>
</div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<script type="text/javascript">
				$(document).ready(function(){
					initCharTalents();			
				});
			</script>
</div>
</div>
</div>
</div>